<?php
$athleteName = stridebr_person_name_for_display((string)($selectedAthlete['nome_exibicao'] ?? ''), (string)($selectedAthlete['username'] ?? ''), stridebr_t('common.user'), 80);
$canPrescribe = stridebr_db_bool($selectedLink['pode_prescrever'] ?? false);
$canSchedules = stridebr_db_bool($selectedLink['pode_ver_cronograma'] ?? false);
$canActivities = stridebr_db_bool($selectedLink['pode_ver_atividades'] ?? false);
$canFeedback = stridebr_db_bool($selectedLink['pode_ver_feedback'] ?? false);
$calendarByDate = [];
foreach ($athleteCalendar as $calendarItem) $calendarByDate[(string)($calendarItem['data_treino'] ?? '')][] = $calendarItem;
$previousWeek = $weekStartDate->modify('-7 days')->format('Y-m-d');
$nextWeek = $weekStartDate->modify('+7 days')->format('Y-m-d');
?>
<section class="coach-workspace-view coach-athlete-workspace" id="athlete-workspace" tabindex="-1" aria-labelledby="coach-athlete-title">
    <a class="coach-back-link" href="/user/treinador.php?context=coach&amp;view=athletes">← <?php echo stridebr_e(stridebr_t('trainer.workspace.athletes')); ?></a>
    <header class="coach-athlete-header coach-frame">
        <div class="coach-athlete-profile"><img src="<?php echo stridebr_e(treinadorAvatar($selectedAthlete)); ?>" width="64" height="64" decoding="async" alt=""><div><h2 id="coach-athlete-title"><?php echo stridebr_e($athleteName); ?></h2><?php if (!empty($selectedAthlete['username'])): ?><p>@<?php echo stridebr_e((string)$selectedAthlete['username']); ?></p><?php endif; ?></div></div>
        <div class="coach-athlete-header-actions">
            <?php if ($canPrescribe): ?><button type="button" class="primary-button" data-open-prescription><?php echo stridebr_e(stridebr_t('trainer.workspace.add_workout')); ?></button><a class="secondary-button" href="/user/treinador.php?context=coach&amp;view=library&amp;library_tab=plans"><?php echo stridebr_e(stridebr_t('trainer.workspace.apply_plan')); ?></a><?php endif; ?>
            <details class="trainer-more-menu"><summary aria-label="<?php echo stridebr_e(stridebr_t('schedule.more_actions')); ?>">•••</summary><div><form method="POST" data-confirm="<?php echo stridebr_e(stridebr_t('trainer.end_athlete_confirm')); ?>"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="end_link"><input type="hidden" name="idvinculo" value="<?php echo stridebr_e((string)$selectedLink['idvinculo']); ?>"><button type="submit" class="is-danger"><?php echo stridebr_e(stridebr_t('trainer.end_link')); ?></button></form></div></details>
        </div>
    </header>
    <nav class="coach-athlete-subnav" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.athlete_navigation')); ?>">
        <?php foreach (['summary'=>'trainer.workspace.summary','calendar'=>'trainer.workspace.calendar','schedules'=>'trainer.workspace.schedules','activities'=>'trainer.workspace.activities'] as $key=>$label): ?>
            <a href="/user/treinador.php?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=<?php echo $key; ?>"<?php echo $athleteTab===$key?' aria-current="page" class="is-active"':''; ?>><?php echo stridebr_e(stridebr_t($label)); ?></a>
        <?php endforeach; ?>
    </nav>

    <?php if ($applyModelData !== []): ?>
        <section class="coach-frame coach-context-action" aria-labelledby="coach-apply-model-title"><div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.workspace.from_library')); ?></span><h3 id="coach-apply-model-title"><?php echo stridebr_e((string)($applyModelData['nome'] ?? '')); ?></h3></div><form method="POST" class="coach-apply-form"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="apply_model"><input type="hidden" name="idatleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><input type="hidden" name="idtreino_modelo" value="<?php echo stridebr_e($applyModelId); ?>"><label><?php echo stridebr_e(stridebr_t('common.date')); ?><input type="date" name="data_treino" value="<?php echo stridebr_e($defaultDate); ?>" required></label><label><?php echo stridebr_e(stridebr_t('common.time')); ?><input type="time" name="hora_inicio"></label><div class="coach-row-actions"><button name="submit_mode" value="draft" class="secondary-button" type="submit"><?php echo stridebr_e(stridebr_t('trainer.workspace.save_draft')); ?></button><button name="submit_mode" value="publish" class="primary-button" type="submit"><?php echo stridebr_e(stridebr_t('trainer.workspace.publish_athlete')); ?></button></div></form></section>
    <?php endif; ?>

    <?php if ($planSourceId !== ''): ?>
        <section class="coach-frame coach-context-action" aria-labelledby="coach-plan-apply-title">
            <div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.workspace.apply_plan')); ?></span><h3 id="coach-plan-apply-title"><?php echo stridebr_e((string)($planPreview['source']['nome'] ?? stridebr_t('trainer.workspace.schedule'))); ?></h3></div>
            <?php if ($planPreview === null): ?>
                <form method="GET" class="coach-apply-form"><input type="hidden" name="context" value="coach"><input type="hidden" name="view" value="athlete"><input type="hidden" name="id" value="<?php echo stridebr_e($selectedAthleteId); ?>"><input type="hidden" name="plan_source" value="<?php echo stridebr_e($planSourceId); ?>"><label><?php echo stridebr_e(stridebr_t('trainer.workspace.start_date')); ?><input type="date" name="plan_start" value="<?php echo stridebr_e($defaultDate); ?>" required></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.end_date')); ?><input type="date" name="plan_end"></label><button class="primary-button" type="submit"><?php echo stridebr_e(stridebr_t('trainer.workspace.preview')); ?></button></form>
            <?php else: ?>
                <div class="coach-plan-summary"><strong><?php echo (int)$planPreview['total']; ?> <?php echo stridebr_e(stridebr_t('trainer.workspace.workouts')); ?></strong><span><?php echo stridebr_e(stridebr_format_date_short((string)$planPreview['start'])); ?> – <?php echo stridebr_e(stridebr_format_date_short((string)$planPreview['end'])); ?></span><span><?php echo count($planPreview['conflicts'] ?? []); ?> <?php echo stridebr_e(stridebr_t('trainer.workspace.conflict_dates')); ?></span></div>
                <div class="coach-plan-preview" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.preview')); ?>"><?php foreach (array_slice($planPreview['occurrences'] ?? [],0,60) as $occ): ?><article><time datetime="<?php echo stridebr_e((string)$occ['data_treino']); ?>"><?php echo stridebr_e(stridebr_format_date_short((string)$occ['data_treino'])); ?></time><strong><?php echo stridebr_e((string)$occ['titulo']); ?></strong><?php if ((int)($occ['conflict_count']??0)>0): ?><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.workspace.date_conflict')); ?></span><?php endif; ?></article><?php endforeach; ?></div>
                <form method="POST" class="coach-plan-confirm"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="apply_plan"><input type="hidden" name="idatleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><input type="hidden" name="idcronograma" value="<?php echo stridebr_e($planSourceId); ?>"><input type="hidden" name="data_inicio" value="<?php echo stridebr_e((string)$planPreview['start']); ?>"><input type="hidden" name="data_fim" value="<?php echo stridebr_e((string)$planPreview['end']); ?>"><input type="hidden" name="idempotency_key" value="<?php echo stridebr_e(bin2hex(random_bytes(16))); ?>"><a class="secondary-button" href="/user/treinador.php?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=calendar"><?php echo stridebr_e(stridebr_t('common.back')); ?></a><button type="submit" name="submit_mode" value="draft" class="secondary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.save_draft')); ?></button><button type="submit" name="submit_mode" value="publish" class="primary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.apply_anyway')); ?></button></form>
            <?php endif; ?>
        </section>
    <?php endif; ?>

    <?php if ($athleteTab === 'summary'): ?>
        <div class="coach-athlete-summary-grid">
            <section class="coach-frame coach-summary-metrics"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.this_week')); ?></h3></header><div class="coach-stat-grid is-compact"><article class="coach-stat"><strong><?php echo (int)($athleteSummary['planned']??0); ?></strong><span><?php echo stridebr_e(stridebr_t('trainer.workspace.planned')); ?></span></article><article class="coach-stat"><strong><?php echo (int)($athleteSummary['completed']??0); ?></strong><span><?php echo stridebr_e(stridebr_t('trainer.workspace.completed')); ?></span></article><article class="coach-stat"><strong><?php echo $canActivities ? (int)($athleteSummary['strength']??0) : '—'; ?></strong><span><?php echo stridebr_e($canActivities?stridebr_t('trainer.workspace.strength_sessions'):stridebr_t('trainer.workspace.no_access')); ?></span></article></div></section>
            <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.next_workout')); ?></h3></header><?php $nextWorkout=null; foreach($selectedPrescriptions as $p){if((string)$p['status']==='publicado' && (string)$p['data_treino']>=date('Y-m-d')){$nextWorkout=$p;break;}} ?><?php if ($nextWorkout): ?><div class="coach-featured-workout"><strong><?php echo stridebr_e((string)$nextWorkout['titulo']); ?></strong><span><?php echo stridebr_e(stridebr_format_date_short((string)$nextWorkout['data_treino'])); ?><?php echo $nextWorkout['hora_inicio']?' · '.stridebr_e(substr((string)$nextWorkout['hora_inicio'],0,5)):''; ?></span><a href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;workout=<?php echo rawurlencode((string)$nextWorkout['idagendamento']); ?>#coach-workout-review"><?php echo stridebr_e(stridebr_t('common.open')); ?></a></div><?php else: ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_next_workout')); ?></p><?php endif; ?></section>
            <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.recent_feedback')); ?></h3></header><?php if (!$canFeedback): ?><p class="coach-no-access"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_access')); ?></p><?php else: ?><?php $feedbackRows=array_values(array_filter($selectedPrescriptions,static fn(array $x):bool=>!empty($x['feedback_em']))); ?><?php if ($feedbackRows===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_feedback')); ?></p><?php endif; ?><?php foreach(array_slice($feedbackRows,0,4) as $fb): ?><article class="coach-feedback-snippet"><strong><?php echo stridebr_e((string)$fb['titulo']); ?></strong><?php if (!empty($fb['nota_atleta'])): ?><span><?php echo (int)$fb['nota_atleta']; ?>/5</span><?php endif; ?><?php if (!empty($fb['feedback_atleta'])): ?><p><?php echo stridebr_e((string)$fb['feedback_atleta']); ?></p><?php endif; ?></article><?php endforeach; ?><?php endif; ?></section>
        </div>
        <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.permissions')); ?></h3></header><div class="coach-permission-list"><span><?php echo stridebr_e(stridebr_t('trainer.prescribe_workout')); ?>: <strong><?php echo stridebr_e(stridebr_t($canPrescribe?'common.yes':'common.no')); ?></strong></span><span><?php echo stridebr_e(stridebr_t('trainer.view_schedules_short')); ?>: <strong><?php echo stridebr_e(stridebr_t($canSchedules?'common.yes':'common.no')); ?></strong></span><span><?php echo stridebr_e(stridebr_t('trainer.view_activities_short')); ?>: <strong><?php echo stridebr_e(stridebr_t($canActivities?'common.yes':'common.no')); ?></strong></span><span><?php echo stridebr_e(stridebr_t('trainer.view_feedback_short')); ?>: <strong><?php echo stridebr_e(stridebr_t($canFeedback?'common.yes':'common.no')); ?></strong></span></div></section>
    <?php elseif ($athleteTab === 'calendar'): ?>
        <section class="coach-frame coach-calendar-frame">
            <header class="coach-calendar-heading"><div><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.week_of',['date'=>stridebr_format_date_short($weekStart)])); ?></h3><span><?php echo stridebr_e(stridebr_format_date_short($weekStart)); ?> – <?php echo stridebr_e(stridebr_format_date_short($weekEnd)); ?></span></div><nav aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.week_navigation')); ?>"><a class="icon-button" href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=calendar&amp;week_start=<?php echo $previousWeek; ?>" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.previous_week')); ?>">‹</a><a class="secondary-button" href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=calendar"><?php echo stridebr_e(stridebr_t('common.today')); ?></a><a class="icon-button" href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=calendar&amp;week_start=<?php echo $nextWeek; ?>" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.next_week')); ?>">›</a></nav></header>
            <div class="coach-week-grid">
                <?php for($day=0;$day<7;$day++): $date=$weekStartDate->modify('+'.$day.' days'); $iso=$date->format('Y-m-d'); $dayItems=$calendarByDate[$iso]??[]; ?>
                    <section class="coach-day<?php echo $iso===date('Y-m-d')?' is-today':''; ?>" data-date="<?php echo $iso; ?>"><header><span><?php echo stridebr_e(strtoupper(stridebr_weekday_names()[(int)$date->format('N')] ?? $date->format('D'))); ?></span><strong><?php echo $date->format('d'); ?></strong></header><div class="coach-day-items"><?php foreach($dayItems as $item): ?><article class="coach-calendar-workout is-<?php echo stridebr_e((string)($item['workspace_source']??'scheduled')); ?>"><strong><?php echo stridebr_e((string)($item['titulo']??$item['nome']??stridebr_t('trainer.workspace.workout'))); ?></strong><?php if (!empty($item['hora_inicio'])): ?><span><?php echo stridebr_e(substr((string)$item['hora_inicio'],0,5)); ?></span><?php endif; ?><small><?php echo stridebr_e(($item['workspace_source']??'')==='athlete_schedule'?stridebr_t('trainer.workspace.athlete_schedule'):stridebr_t('trainer.workspace.coach_workout')); ?></small><?php if (($item['workspace_source']??'')!=='athlete_schedule'): ?><a href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=calendar&amp;week_start=<?php echo $weekStart; ?>&amp;workout=<?php echo rawurlencode((string)$item['idagendamento']); ?>#coach-workout-review"><?php echo stridebr_e(stridebr_t(!empty($item['capabilities']['analyze'])?'trainer.workspace.analyze':'common.open')); ?></a><?php endif; ?></article><?php endforeach; ?><?php if ($dayItems===[]): ?><span class="coach-day-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_workout')); ?></span><?php endif; ?></div><?php if ($canPrescribe): ?><button type="button" class="coach-day-add" data-coach-create-date="<?php echo $iso; ?>" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.add_on_date',['date'=>stridebr_format_date_short($iso)])); ?>">+</button><?php endif; ?></section>
                <?php endfor; ?>
            </div>
        </section>
    <?php elseif ($athleteTab === 'schedules'): ?>
        <div class="coach-two-column">
            <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.athlete_schedules')); ?></h3><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.read_only')); ?></span></header><?php if (!$canSchedules): ?><p class="coach-no-access"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_access')); ?></p><?php elseif ($selectedSchedules===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.no_active_schedules')); ?></p><?php else: ?><div class="coach-dense-list"><?php foreach($selectedSchedules as $schedule): ?><article><div class="coach-list-main"><strong><?php echo stridebr_e((string)$schedule['nome']); ?></strong><span><?php echo stridebr_e((string)($schedule['descricao']??'')); ?></span></div><a href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=schedules&amp;view_schedule=<?php echo rawurlencode((string)$schedule['idcronograma']); ?>"><?php echo stridebr_e(stridebr_t('common.open')); ?></a></article><?php endforeach; ?></div><?php endif; ?></section>
            <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.applied_plans')); ?></h3></header><?php if ($selectedApplications===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_applied_plans')); ?></p><?php else: ?><div class="coach-dense-list"><?php foreach($selectedApplications as $app): ?><article><div class="coach-list-main"><strong><?php echo stridebr_e((string)$app['nome_snapshot']); ?></strong><span><?php echo stridebr_e(stridebr_format_date_short((string)$app['data_inicio'])); ?> – <?php echo stridebr_e(stridebr_format_date_short((string)$app['data_fim'])); ?></span><small><?php echo (int)$app['completed_total']; ?> / <?php echo (int)$app['workouts_total']; ?> <?php echo stridebr_e(stridebr_t('trainer.workspace.completed_short')); ?></small></div><?php if ((string)$app['status']==='ativo' && $canPrescribe): ?><form method="POST" data-confirm="<?php echo stridebr_e(stridebr_t('trainer.workspace.remove_plan_confirm')); ?>"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="remove_plan"><input type="hidden" name="idaplicacao" value="<?php echo stridebr_e((string)$app['idaplicacao']); ?>"><input type="hidden" name="redirect_atleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><button type="submit" class="text-button is-danger"><?php echo stridebr_e(stridebr_t('trainer.workspace.remove_plan')); ?></button></form><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?></section>
        </div>
        <?php if ($readonlySchedule !== []): ?><section class="coach-frame trainer-readonly-detail"><header><div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.read_only')); ?></span><h3><?php echo stridebr_e((string)$readonlySchedule['nome']); ?></h3></div></header><?php if (!empty($readonlySchedule['descricao'])): ?><p><?php echo nl2br(stridebr_e((string)$readonlySchedule['descricao'])); ?></p><?php endif; ?><div class="coach-dense-list"><?php foreach(($readonlySchedule['treinos']??[]) as $workout): ?><article><div class="coach-list-main"><strong><?php echo stridebr_e((string)$workout['nome']); ?></strong><small><?php echo stridebr_e(stridebr_weekday_names()[(int)$workout['dia_semana']]??''); ?><?php echo $workout['hora_inicio']?' · '.stridebr_e(substr((string)$workout['hora_inicio'],0,5)):''; ?></small></div></article><?php endforeach; ?></div></section><?php endif; ?>
    <?php else: ?>
        <section class="coach-frame"><header><h3><?php echo stridebr_e(stridebr_t('trainer.workspace.activities')); ?></h3></header><?php if (!$canActivities): ?><p class="coach-no-access"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_access')); ?></p><?php elseif ($selectedActivities===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.no_shared_activities')); ?></p><?php else: ?><div class="coach-dense-list"><?php foreach($selectedActivities as $activity): ?><article><div class="coach-list-main"><strong><?php echo stridebr_e((string)$activity['titulo']); ?></strong><span><?php echo stridebr_e(stridebr_sport_name((string)$activity['modalidade_slug'],(string)$activity['modalidade_nome'])); ?></span><small><?php echo stridebr_e(stridebr_format_datetime_short((string)$activity['data_inicio'])); ?></small></div><a href="?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode($selectedAthleteId); ?>&amp;tab=activities&amp;view_activity=<?php echo rawurlencode((string)$activity['idregistro']); ?>"><?php echo stridebr_e(stridebr_t('common.open')); ?></a></article><?php endforeach; ?></div><?php endif; ?></section>
        <?php if ($readonlyActivity !== []): ?><section class="coach-frame trainer-readonly-detail"><header><h3><?php echo stridebr_e((string)$readonlyActivity['titulo']); ?></h3><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.read_only')); ?></span></header><p><?php echo stridebr_e(stridebr_format_datetime_short((string)$readonlyActivity['data_inicio'])); ?> · <?php echo stridebr_e(stridebr_sport_name((string)$readonlyActivity['modalidade_slug'],(string)$readonlyActivity['modalidade_nome'])); ?></p><?php if (($readonlyActivity['distancia_metros']??null)!==null): ?><p><?php echo stridebr_e(stridebr_t('activity.distance')); ?>: <?php echo stridebr_e(atividadeContextoFormatarDistancia((float)$readonlyActivity['distancia_metros'],atividadeContextoEsportivo((string)$readonlyActivity['modalidade_slug']))); ?></p><?php endif; ?><?php if (!empty($readonlyActivity['observacoes'])): ?><p><?php echo nl2br(stridebr_e((string)$readonlyActivity['observacoes'])); ?></p><?php endif; ?></section><?php endif; ?>
    <?php endif; ?>

    <?php if ($workoutComparison !== null): ?>
        <section class="coach-frame coach-workout-review" id="coach-workout-review" tabindex="-1"><header><div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.workspace.planned_actual')); ?></span><h3><?php echo stridebr_e((string)$workoutComparison['workout']['titulo']); ?></h3></div></header>
            <?php $endurance=$workoutComparison['endurance']??[]; if (array_filter([$endurance['planned_duration_s']??null,$endurance['actual_duration_s']??null,$endurance['planned_distance_m']??null,$endurance['actual_distance_m']??null],static fn($v)=>$v!==null)!==[]): ?><div class="coach-comparison-summary"><?php foreach ([['trainer.workspace.duration','planned_duration_s','actual_duration_s'],['trainer.workspace.distance','planned_distance_m','actual_distance_m'],['trainer.workspace.rpe',null,'actual_rpe']] as [$label,$pkey,$akey]): $pv=$pkey?$endurance[$pkey]??null:null;$av=$endurance[$akey]??null;if($pv===null&&$av===null)continue; ?><article><span><?php echo stridebr_e(stridebr_t($label)); ?></span><div><small><?php echo stridebr_e(stridebr_t('trainer.workspace.planned')); ?></small><strong><?php echo $pv===null?'—':stridebr_e((string)$pv); ?></strong></div><div><small><?php echo stridebr_e(stridebr_t('trainer.workspace.actual')); ?></small><strong><?php echo $av===null?'—':stridebr_e((string)$av); ?></strong></div></article><?php endforeach; ?></div><?php endif; ?>
            <?php foreach (($workoutComparison['exercises']??[]) as $exercise): ?><div class="coach-exercise-comparison"><h4><?php echo stridebr_e((string)$exercise['name']); ?></h4><div class="coach-comparison-table-wrap"><table class="coach-comparison-table"><thead><tr><th><?php echo stridebr_e(stridebr_t('trainer.workspace.set')); ?></th><th><?php echo stridebr_e(stridebr_t('trainer.workspace.planned')); ?></th><th><?php echo stridebr_e(stridebr_t('trainer.workspace.actual')); ?></th></tr></thead><tbody><?php foreach($exercise['sets'] as $set): ?><tr><th>#<?php echo (int)$set['number']; ?></th><td><?php echo stridebr_e(treinadorWorkspaceFormatarSet($set['planned']??[])); ?></td><td><?php echo stridebr_e(treinadorWorkspaceFormatarSet($set['actual']??[])); ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endforeach; ?>
            <?php if ($canFeedback): ?><section class="coach-feedback-comments"><div><h4><?php echo stridebr_e(stridebr_t('trainer.workspace.athlete_feedback')); ?></h4><?php $workout=$workoutComparison['workout']; ?><?php if (!empty($workout['nota_atleta'])||!empty($workout['feedback_atleta'])): ?><p><strong><?php echo !empty($workout['nota_atleta'])?(int)$workout['nota_atleta'].'/5':''; ?></strong><?php echo !empty($workout['feedback_atleta'])?' '.stridebr_e((string)$workout['feedback_atleta']):''; ?></p><?php else: ?><p class="coach-empty">—</p><?php endif; ?></div><div><h4><?php echo stridebr_e(stridebr_t('trainer.workspace.comments')); ?></h4><div class="coach-comment-list"><?php foreach($workoutComments as $comment): ?><article><header><strong><?php echo stridebr_e((string)$comment['autor_nome']); ?></strong><span><?php echo stridebr_e(stridebr_t($comment['autor_papel']==='coach'?'trainer.workspace.coach_role':'trainer.workspace.athlete_role')); ?> · <?php echo stridebr_e(stridebr_format_datetime_short((string)$comment['criado_em'])); ?></span></header><p><?php echo nl2br(stridebr_e((string)$comment['texto'])); ?></p></article><?php endforeach; ?></div><form method="POST" class="coach-comment-form"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="create_comment"><input type="hidden" name="idagendamento" value="<?php echo stridebr_e((string)$workoutComparison['workout']['idagendamento']); ?>"><input type="hidden" name="redirect_atleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><label><?php echo stridebr_e(stridebr_t('trainer.workspace.write_comment')); ?><textarea name="texto" maxlength="2000" required></textarea></label><button class="primary-button" type="submit"><?php echo stridebr_e(stridebr_t('common.send')); ?></button></form></div></section><?php endif; ?>
        </section>
    <?php endif; ?>
</section>
