<?php
$athleteViewTitle = $coachView === 'calendar' ? 'trainer.workspace.calendar' : 'trainer.workspace.athletes';
?>
<section class="coach-workspace-view" aria-labelledby="coach-athletes-title">
    <header class="coach-view-heading"><div><h2 id="coach-athletes-title"><?php echo stridebr_e(stridebr_t($athleteViewTitle)); ?></h2><p><?php echo stridebr_e(stridebr_t($coachView === 'calendar' ? 'trainer.workspace.calendar_choose' : 'trainer.workspace.athletes_help')); ?></p></div><details class="coach-invite"><summary class="primary-button"><?php echo stridebr_e(stridebr_t('trainer.invite_athlete')); ?></summary><form method="POST" class="coach-inline-form"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="invite_athlete"><label><?php echo stridebr_e(stridebr_t('common.username')); ?><input name="username" autocomplete="off" placeholder="@username" required></label><button type="submit" class="primary-button"><?php echo stridebr_e(stridebr_t('friends.send_invite')); ?></button></form></details></header>
    <form method="GET" class="coach-toolbar" role="search">
        <input type="hidden" name="context" value="coach"><input type="hidden" name="view" value="<?php echo stridebr_e($coachView); ?>">
        <label class="coach-search"><span><?php echo stridebr_e(stridebr_t('trainer.workspace.search_athlete')); ?></span><input type="search" name="q" value="<?php echo stridebr_e($coachSearch); ?>" placeholder="<?php echo stridebr_e(stridebr_t('trainer.workspace.search_athlete_placeholder')); ?>"></label>
        <label><span><?php echo stridebr_e(stridebr_t('common.filter')); ?></span><select name="filter"><option value="all"<?php echo $coachFilter==='all'?' selected':''; ?>><?php echo stridebr_e(stridebr_t('common.all')); ?></option><option value="today"<?php echo $coachFilter==='today'?' selected':''; ?>><?php echo stridebr_e(stridebr_t('trainer.workspace.filter_today')); ?></option><option value="attention"<?php echo $coachFilter==='attention'?' selected':''; ?>><?php echo stridebr_e(stridebr_t('trainer.workspace.filter_attention')); ?></option><option value="pending"<?php echo $coachFilter==='pending'?' selected':''; ?>><?php echo stridebr_e(stridebr_t('trainer.workspace.filter_pending')); ?></option></select></label>
        <button type="submit" class="secondary-button"><?php echo stridebr_e(stridebr_t('common.apply')); ?></button>
    </form>
    <div class="coach-athlete-table-wrap">
        <table class="coach-athlete-table">
            <caption class="sr-only"><?php echo stridebr_e(stridebr_t('trainer.workspace.athlete_table_caption')); ?></caption>
            <thead><tr><th scope="col"><?php echo stridebr_e(stridebr_t('trainer.athlete')); ?></th><th scope="col"><?php echo stridebr_e(stridebr_t('trainer.workspace.this_week')); ?></th><th scope="col"><?php echo stridebr_e(stridebr_t('trainer.workspace.next_workout')); ?></th><th scope="col"><?php echo stridebr_e(stridebr_t('trainer.workspace.last_activity')); ?></th><th scope="col"><?php echo stridebr_e(stridebr_t('trainer.workspace.attention_label')); ?></th><th scope="col"><span class="sr-only"><?php echo stridebr_e(stridebr_t('common.actions')); ?></span></th></tr></thead>
            <tbody>
            <?php foreach (($coachAthletes['items'] ?? []) as $item): ?>
                <?php $accepted=(string)$item['status']==='aceito'; $targetTab=$coachView==='calendar'?'calendar':'summary'; ?>
                <tr>
                    <th scope="row"><div class="coach-athlete-identity"><img src="<?php echo stridebr_e(treinadorAvatar($item)); ?>" width="40" height="40" loading="lazy" decoding="async" alt=""><div><a href="/user/treinador.php?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode((string)$item['idatleta']); ?>&amp;tab=<?php echo $targetTab; ?><?php echo $applyModelId!==''?'&amp;apply_model='.rawurlencode($applyModelId):''; ?><?php echo $planSourceId!==''?'&amp;plan_source='.rawurlencode($planSourceId):''; ?>"><?php echo stridebr_e((string)$item['nome_exibicao']); ?></a><?php if (!empty($item['username'])): ?><span>@<?php echo stridebr_e((string)$item['username']); ?></span><?php endif; ?></div></div></th>
                    <td data-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.this_week')); ?>"><?php echo $accepted ? (int)$item['week_completed'].' / '.(int)$item['week_planned'] : stridebr_e(stridebr_t('trainer.awaiting_response')); ?></td>
                    <td data-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.next_workout')); ?>"><?php if (!$accepted): ?>—<?php elseif (!empty($item['next_title'])): ?><strong><?php echo stridebr_e((string)$item['next_title']); ?></strong><small><?php echo stridebr_e(stridebr_format_date_short((string)$item['next_date'])); ?><?php echo !empty($item['next_time'])?' · '.stridebr_e(substr((string)$item['next_time'],0,5)):''; ?></small><?php else: ?>—<?php endif; ?></td>
                    <td data-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.last_activity')); ?>"><?php if (!$accepted): ?>—<?php elseif (!stridebr_db_bool($item['pode_ver_atividades']??false)): ?><span class="coach-no-access"><?php echo stridebr_e(stridebr_t('trainer.workspace.no_access')); ?></span><?php elseif (!empty($item['last_activity_at'])): ?><?php echo stridebr_e(stridebr_format_datetime_short((string)$item['last_activity_at'])); ?><?php else: ?>—<?php endif; ?></td>
                    <td data-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.attention_label')); ?>"><?php if (!$accepted): ?><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.workspace.pending')); ?></span><?php else: ?><?php if (stridebr_db_bool($item['pode_ver_feedback']??false) && (int)($item['feedback_count']??0)>0): ?><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.workspace.feedback_received')); ?></span><?php elseif ((int)($item['missed_count']??0)>0): ?><span class="status-pill"><?php echo stridebr_e(stridebr_t('trainer.workspace.missed_workout')); ?></span><?php else: ?>—<?php endif; ?><?php endif; ?></td>
                    <td class="coach-athlete-actions"><?php if ($accepted): ?><a class="icon-button" aria-label="<?php echo stridebr_e(stridebr_t('trainer.open_athlete')); ?>" href="/user/treinador.php?context=coach&amp;view=athlete&amp;id=<?php echo rawurlencode((string)$item['idatleta']); ?>&amp;tab=<?php echo $targetTab; ?><?php echo $applyModelId!==''?'&amp;apply_model='.rawurlencode($applyModelId):''; ?><?php echo $planSourceId!==''?'&amp;plan_source='.rawurlencode($planSourceId):''; ?>">›</a><?php elseif ((string)$item['solicitado_por']==='atleta'): ?><div class="coach-pending-actions"><form method="POST"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="accept_link"><input type="hidden" name="idvinculo" value="<?php echo stridebr_e((string)$item['idvinculo']); ?>"><button class="text-button" type="submit"><?php echo stridebr_e(stridebr_t('trainer.accept_athlete')); ?></button></form><form method="POST"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="reject_link"><input type="hidden" name="idvinculo" value="<?php echo stridebr_e((string)$item['idvinculo']); ?>"><button class="text-button is-danger" type="submit"><?php echo stridebr_e(stridebr_t('friends.decline')); ?></button></form></div><?php endif; ?></td>
                </tr>
            <?php endforeach; ?>
            <?php if (($coachAthletes['items'] ?? []) === []): ?><tr><td colspan="6" class="coach-table-empty"><?php echo stridebr_e(stridebr_t('trainer.no_athletes')); ?></td></tr><?php endif; ?>
            </tbody>
        </table>
    </div>
    <?php if (($coachAthletes['pages'] ?? 1) > 1): ?><nav class="coach-pagination" aria-label="<?php echo stridebr_e(stridebr_t('common.pagination')); ?>"><?php for($p=1;$p<=(int)$coachAthletes['pages'];$p++): ?><a<?php echo $p===(int)$coachAthletes['page']?' aria-current="page" class="is-active"':''; ?> href="?context=coach&amp;view=<?php echo stridebr_e($coachView); ?>&amp;q=<?php echo rawurlencode($coachSearch); ?>&amp;filter=<?php echo rawurlencode($coachFilter); ?>&amp;page=<?php echo $p; ?>"><?php echo $p; ?></a><?php endfor; ?></nav><?php endif; ?>
</section>
