<?php
$modalRows = $editingPrescription['exercicios'] ?? [['idexercicio'=>'','nome_snapshot'=>'','series'=>'','repeticoes'=>'','carga'=>'','duracao'=>'','distancia'=>'','descanso'=>'','observacoes'=>'']];
$modalDate = (string)($editingPrescription['data_treino'] ?? $defaultDate);
?>
<div class="trainer-prescription-modal" data-prescription-modal<?php echo $editingPrescription !== [] ? ' data-auto-open="1"' : ''; ?> hidden>
    <section class="trainer-prescription-dialog" role="dialog" aria-modal="true" aria-labelledby="trainer-prescription-title">
        <header class="trainer-prescription-modal-heading"><div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.prescription')); ?></span><h2 id="trainer-prescription-title"><?php echo stridebr_e(stridebr_t($editingPrescription !== []?'trainer.edit_prescription':'trainer.workspace.create_workout')); ?></h2></div><button type="button" class="icon-button" data-close-prescription aria-label="<?php echo stridebr_e(stridebr_t('common.close')); ?>">×</button></header>
        <form method="POST" class="trainer-prescription-form"><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="<?php echo $editingPrescription!==[]?'edit_prescription':'create_prescription'; ?>"><input type="hidden" name="idatleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><?php if($editingPrescription!==[]): ?><input type="hidden" name="idagendamento" value="<?php echo stridebr_e((string)$editingPrescription['idagendamento']); ?>"><?php endif; ?>
            <div class="coach-form-grid"><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('common.title')); ?><input name="titulo" maxlength="120" required value="<?php echo stridebr_e((string)($editingPrescription['titulo']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.sport')); ?><select name="idmodalidade"><option value="">—</option><?php foreach($prescriptionModalities as $modality): ?><option value="<?php echo stridebr_e((string)$modality['idmodalidade']); ?>"<?php echo (string)($editingPrescription['idmodalidade']??'')===(string)$modality['idmodalidade']?' selected':''; ?>><?php echo stridebr_e((string)$modality['nome']); ?></option><?php endforeach; ?></select></label><label><?php echo stridebr_e(stridebr_t('common.date')); ?><input type="date" name="data_treino" value="<?php echo stridebr_e($modalDate); ?>" required data-prescription-date></label><label><?php echo stridebr_e(stridebr_t('common.time')); ?><input type="time" name="hora_inicio" value="<?php echo stridebr_e(substr((string)($editingPrescription['hora_inicio']??''),0,5)); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.duration_minutes')); ?><input type="number" name="duracao_prevista_min" min="1" max="1440" value="<?php echo stridebr_e((string)($editingPrescription['duracao_prevista_min']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.planned_distance_m')); ?><input type="number" step="0.001" min="0" name="distancia_prevista_m" value="<?php echo stridebr_e((string)($editingPrescription['distancia_prevista_m']??'')); ?>"></label><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('common.description')); ?><textarea name="descricao" maxlength="5000"><?php echo stridebr_e((string)($editingPrescription['descricao']??'')); ?></textarea></label></div>
            <div class="trainer-prescription-exercises" data-prescription-exercises><div class="trainer-prescription-exercise-head"><strong><?php echo stridebr_e(stridebr_t('trainer.workspace.exercises')); ?></strong><button type="button" class="text-button" data-add-prescription-exercise>+ <?php echo stridebr_e(stridebr_t('trainer.workspace.add_exercise')); ?></button></div><?php foreach($modalRows as $row): ?><div class="trainer-prescription-exercise" data-prescription-exercise><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('exercise.field.name')); ?><input type="hidden" name="exercise_id[]" data-exercise-id value="<?php echo stridebr_e((string)($row['idexercicio']??'')); ?>"><input name="exercise_name[]" autocomplete="off" value="<?php echo stridebr_e((string)($row['nome_snapshot']??$row['nome']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.sets')); ?><input type="number" min="1" max="99" name="exercise_series[]" value="<?php echo stridebr_e((string)($row['series']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.reps')); ?><input name="exercise_reps[]" maxlength="40" value="<?php echo stridebr_e((string)($row['repeticoes']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.load')); ?><input name="exercise_load[]" maxlength="40" value="<?php echo stridebr_e((string)($row['carga']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.exercise_duration')); ?><input name="exercise_duration[]" maxlength="40" value="<?php echo stridebr_e((string)($row['duracao']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.exercise_distance')); ?><input name="exercise_distance[]" maxlength="40" value="<?php echo stridebr_e((string)($row['distancia']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.rest')); ?><input name="exercise_rest[]" maxlength="40" value="<?php echo stridebr_e((string)($row['descanso']??'')); ?>"></label><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('common.notes')); ?><input name="exercise_notes[]" maxlength="1000" value="<?php echo stridebr_e((string)($row['observacoes']??'')); ?>"></label><button type="button" class="icon-button" data-remove-prescription-exercise aria-label="<?php echo stridebr_e(stridebr_t('common.remove')); ?>">×</button></div><?php endforeach; ?></div>
            <footer class="trainer-prescription-actions"><button type="button" class="secondary-button" data-close-prescription><?php echo stridebr_e(stridebr_t('common.cancel')); ?></button><button type="submit" name="submit_mode" value="draft" class="secondary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.save_draft')); ?></button><button type="submit" name="submit_mode" value="publish" class="primary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.publish_athlete')); ?></button></footer>
        </form>
    </section>
</div>
