<section class="coach-workspace-view" aria-labelledby="coach-library-title">
    <header class="coach-view-heading"><div><h2 id="coach-library-title"><?php echo stridebr_e(stridebr_t('trainer.workspace.library')); ?></h2><p><?php echo stridebr_e(stridebr_t('trainer.workspace.library_help')); ?></p></div><a class="secondary-button" href="/user/biblioteca.php"><?php echo stridebr_e(stridebr_t('trainer.workspace.manage_library')); ?></a></header>
    <nav class="coach-library-tabs" aria-label="<?php echo stridebr_e(stridebr_t('trainer.workspace.library')); ?>"><a href="?context=coach&amp;view=library&amp;library_tab=workouts"<?php echo $coachLibraryTab==='workouts'?' aria-current="page" class="is-active"':''; ?>><?php echo stridebr_e(stridebr_t('trainer.workspace.workouts')); ?></a><a href="?context=coach&amp;view=library&amp;library_tab=plans"<?php echo $coachLibraryTab==='plans'?' aria-current="page" class="is-active"':''; ?>><?php echo stridebr_e(stridebr_t('trainer.workspace.schedules')); ?></a></nav>
    <div class="coach-library-list">
        <?php if ($coachLibraryTab === 'workouts'): ?>
            <?php foreach (($coachLibrary['workouts'] ?? []) as $item): ?><article class="coach-library-row"><div><strong><?php echo stridebr_e((string)($item['nome']??$item['titulo']??'')); ?></strong><small><?php echo stridebr_e((string)($item['descricao']??'')); ?></small></div><div class="coach-row-actions"><a class="secondary-button" href="/user/biblioteca.php"><?php echo stridebr_e(stridebr_t('common.edit')); ?></a><a class="primary-button" href="/user/treinador.php?context=coach&amp;view=athletes&amp;apply_model=<?php echo rawurlencode((string)$item['idtreino_modelo']); ?>"><?php echo stridebr_e(stridebr_t('trainer.workspace.apply_to_athlete')); ?></a></div></article><?php endforeach; ?>
            <?php if (($coachLibrary['workouts'] ?? [])===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.library_workouts_empty')); ?></p><?php endif; ?>
        <?php else: ?>
            <?php foreach (($coachLibrary['schedules'] ?? []) as $item): ?><article class="coach-library-row"><div><strong><?php echo stridebr_e((string)$item['nome']); ?></strong><small><?php echo (int)$item['workouts_total']; ?> <?php echo stridebr_e(stridebr_t('trainer.workspace.workouts')); ?><?php echo !empty($item['descricao'])?' · '.stridebr_e((string)$item['descricao']):''; ?></small></div><div class="coach-row-actions"><a class="secondary-button" href="/user/cronogramatreinos.php?id=<?php echo rawurlencode((string)$item['idcronograma']); ?>"><?php echo stridebr_e(stridebr_t('trainer.workspace.preview')); ?></a><a class="primary-button" href="/user/treinador.php?context=coach&amp;view=athletes&amp;plan_source=<?php echo rawurlencode((string)$item['idcronograma']); ?>"><?php echo stridebr_e(stridebr_t('trainer.workspace.apply')); ?></a></div></article><?php endforeach; ?>
            <?php if (($coachLibrary['schedules'] ?? [])===[]): ?><p class="coach-empty"><?php echo stridebr_e(stridebr_t('trainer.workspace.library_plans_empty')); ?></p><?php endif; ?>
        <?php endif; ?>
    </div>
</section>
