<?php
require_once dirname(__DIR__) . '/workout_builder.php';
$modalRows = is_array($editingPrescription['exercicios'] ?? null) ? $editingPrescription['exercicios'] : [];
$modalDate = (string)($editingPrescription['data_treino'] ?? $defaultDate);
$builderOptions = ['sport_slug' => ''];
?>
<div class="trainer-prescription-modal" data-prescription-modal<?php echo $editingPrescription !== [] ? ' data-auto-open="1"' : ''; ?> hidden>
    <section class="trainer-prescription-dialog" role="dialog" aria-modal="true" aria-labelledby="trainer-prescription-title">
        <header class="trainer-prescription-modal-heading"><div><span class="eyebrow"><?php echo stridebr_e(stridebr_t('trainer.prescription')); ?></span><h2 id="trainer-prescription-title"><?php echo stridebr_e(stridebr_t($editingPrescription !== []?'trainer.edit_prescription':'trainer.workspace.create_workout')); ?></h2></div><button type="button" class="icon-button" data-close-prescription aria-label="<?php echo stridebr_e(stridebr_t('common.close')); ?>">×</button></header>
        <form method="POST" class="trainer-prescription-form workout-builder-shell" data-workout-builder><?php echo stridebr_csrf_field(); ?><input type="hidden" name="action" value="<?php echo $editingPrescription!==[]?'edit_prescription':'create_prescription'; ?>"><input type="hidden" name="idatleta" value="<?php echo stridebr_e($selectedAthleteId); ?>"><?php if($editingPrescription!==[]): ?><input type="hidden" name="idagendamento" value="<?php echo stridebr_e((string)$editingPrescription['idagendamento']); ?>"><?php endif; ?>
            <div class="coach-form-grid"><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('common.title')); ?><input name="titulo" maxlength="120" required value="<?php echo stridebr_e((string)($editingPrescription['titulo']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.sport')); ?><select name="idmodalidade"><option value="">—</option><?php foreach($prescriptionModalities as $modality): ?><option value="<?php echo stridebr_e((string)$modality['idmodalidade']); ?>"<?php echo (string)($editingPrescription['idmodalidade']??'')===(string)$modality['idmodalidade']?' selected':''; ?>><?php echo stridebr_e((string)$modality['nome']); ?></option><?php endforeach; ?></select></label><label><?php echo stridebr_e(stridebr_t('common.date')); ?><input type="date" name="data_treino" value="<?php echo stridebr_e($modalDate); ?>" required data-prescription-date></label><label><?php echo stridebr_e(stridebr_t('common.time')); ?><input type="time" name="hora_inicio" value="<?php echo stridebr_e(substr((string)($editingPrescription['hora_inicio']??''),0,5)); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.duration_minutes')); ?><input type="number" name="duracao_prevista_min" min="1" max="1440" value="<?php echo stridebr_e((string)($editingPrescription['duracao_prevista_min']??'')); ?>"></label><label><?php echo stridebr_e(stridebr_t('trainer.workspace.planned_distance_m')); ?><input type="number" step="0.001" min="0" name="distancia_prevista_m" value="<?php echo stridebr_e((string)($editingPrescription['distancia_prevista_m']??'')); ?>"></label><label class="coach-field-wide"><?php echo stridebr_e(stridebr_t('common.description')); ?><textarea name="descricao" maxlength="5000"><?php echo stridebr_e((string)($editingPrescription['descricao']??'')); ?></textarea></label></div>
            <div class="workout-builder-toolbar"><div class="workout-builder-toolbar-main"><div class="workout-builder-toolbar-title"><strong><?php echo stridebr_e(stridebr_t('workout_builder.title')); ?></strong><span><?php echo count($modalRows); ?> <?php echo stridebr_e(stridebr_t('common.exercises')); ?></span></div><span class="wb-unsaved" data-wb-dirty hidden><?php echo stridebr_e(stridebr_t('workout_builder.unsaved')); ?></span></div><div class="workout-builder-toolbar-actions"><details class="wb-add-menu"><summary class="secondary-button">+ <?php echo stridebr_e(stridebr_t('workout_builder.add')); ?></summary><div class="wb-add-menu-panel"><button type="button" data-wb-add-exercise><?php echo stridebr_e(stridebr_t('workout_builder.add_exercise')); ?></button><div class="wb-add-menu-divider"></div><?php foreach (['warmup','work','interval_group','recovery','cooldown'] as $step): ?><button type="button" data-wb-add-step="<?php echo $step; ?>"><?php echo stridebr_e(workoutBuilderStepLabel($step)); ?></button><?php endforeach; ?></div></details><div class="wb-selection-bar" data-wb-selection hidden><span data-wb-selected-count></span><button type="button" class="secondary-button compact-button" data-wb-create-group="superset"><?php echo stridebr_e(stridebr_t('workout_builder.group.superset')); ?></button><button type="button" class="secondary-button compact-button" data-wb-create-group="circuit"><?php echo stridebr_e(stridebr_t('workout_builder.group.circuit')); ?></button></div></div></div>
            <div class="workout-builder-list" data-wb-list><?php workoutBuilderRender($modalRows, $builderOptions); ?><div class="workout-builder-empty" data-wb-empty<?php echo $modalRows !== [] ? ' hidden' : ''; ?>><strong><?php echo stridebr_e(stridebr_t('workout_builder.empty')); ?></strong><span><?php echo stridebr_e(stridebr_t('workout_builder.empty_help')); ?></span><button type="button" class="secondary-button" data-wb-add-exercise><?php echo stridebr_e(stridebr_t('workout_builder.add_exercise')); ?></button></div></div>
            <template data-wb-card-template><?php echo workoutBuilderRenderCard(['tipo_passo'=>'exercise','tracking_mode'=>'load_reps','metodo_prescricao'=>'standard'], '__INDEX__', $builderOptions); ?></template>
            <div class="wb-a11y-live" data-wb-live aria-live="polite" aria-atomic="true"></div>
            <dialog class="wb-picker" data-wb-picker><div class="wb-picker-head"><h2><?php echo stridebr_e(stridebr_t('workout_builder.add_exercise')); ?></h2><button type="button" data-wb-picker-close aria-label="<?php echo stridebr_e(stridebr_t('workout_builder.close')); ?>">×</button></div><div class="wb-picker-search"><input type="search" data-wb-picker-search placeholder="<?php echo stridebr_e(stridebr_t('workout_builder.search_placeholder')); ?>" autocomplete="off"></div><div class="wb-picker-results" data-wb-picker-results></div></dialog>
            <footer class="trainer-prescription-actions"><button type="button" class="secondary-button" data-close-prescription><?php echo stridebr_e(stridebr_t('common.cancel')); ?></button><button type="submit" name="submit_mode" value="draft" class="secondary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.save_draft')); ?></button><button type="submit" name="submit_mode" value="publish" class="primary-button"><?php echo stridebr_e(stridebr_t('trainer.workspace.publish_athlete')); ?></button></footer>
        </form>
    </section>
</div>
