<?php

declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/src/includes/errors.php';
require_once dirname(__DIR__, 2) . '/src/includes/app.php';
require_once dirname(__DIR__, 2) . '/src/function/teams_surface_provider.php';
$idUsuario = stridebr_require_login();
if (!stridebr_teams_enabled()) stridebr_error_document(404);
require_once dirname(__DIR__, 2) . '/src/config/pg_config.php';
$ref = trim((string) ($_GET['id'] ?? ''));
$competition = $ref !== '' ? stridebr_teams_surface_competition($pdo, $idUsuario, $ref) : null;
if (!$competition) stridebr_error_document(404);
?>
<!doctype html><html lang="<?php echo stridebr_e(stridebr_html_lang()); ?>"><head><?php echo stridebr_ui_boot_script(); ?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="<?php echo stridebr_e(stridebr_asset('/assets/css/style.css')); ?>"><link rel="stylesheet" href="<?php echo stridebr_e(stridebr_asset('/assets/css/institutional.css')); ?>"><link rel="stylesheet" href="<?php echo stridebr_e(stridebr_asset('/assets/css/ui-refresh.css')); ?>"><title><?php echo stridebr_e((string) $competition['display_name']); ?> | StrideBR</title></head><body><div class="container-fluid"><?php require dirname(__DIR__, 2) . '/src/layout/header.php'; ?><main class="main-content"><div class="institutional-shell"><header class="institutional-head"><div><span class="institutional-badge"><?php echo stridebr_e(stridebr_t('teams.institutional')); ?></span><h1><?php echo stridebr_e((string) $competition['display_name']); ?></h1><p><?php echo stridebr_e((string) $competition['start_date']); ?> — <?php echo stridebr_e((string) $competition['end_date']); ?></p></div></header><section class="institutional-card"><h2><?php echo stridebr_e(stridebr_t('teams.my_participation')); ?></h2><div class="institutional-list"><div><span><?php echo stridebr_e(stridebr_t('teams.delegation')); ?></span><strong><?php echo !empty($competition['delegation_member']) ? stridebr_e(stridebr_t('common.yes')) : stridebr_e(stridebr_t('common.no')); ?></strong></div></div></section><section class="institutional-card"><h2><?php echo stridebr_e(stridebr_t('teams.my_entries')); ?></h2><div class="institutional-results"><?php foreach ((array) $competition['entries'] as $entry): ?><article class="institutional-result"><strong><?php echo stridebr_e((string) $entry['program_item']); ?></strong><?php if (!empty($entry['phase'])): ?><p><?php echo stridebr_e((string) $entry['phase']); ?></p><?php endif; ?><?php foreach ((array) $entry['results'] as $result): ?><div class="institutional-meta"><span><?php echo stridebr_e((string) ($result['classification'] ?? '')); ?></span><span><?php echo stridebr_e((string) ($result['result'] ?? '')); ?></span><?php if (!empty($result['medal'])): ?><span><?php echo stridebr_e((string) $result['medal']); ?></span><?php endif; ?><span><?php echo stridebr_e((string) ($result['provenance'] ?? '')); ?></span></div><?php endforeach; ?></article><?php endforeach; ?></div></section></div></main></div><?php require dirname(__DIR__, 2) . '/src/layout/footer.php'; ?></body></html>
