<?php

declare(strict_types=1);
require_once dirname(__DIR__, 3) . '/src/includes/app.php';
$pageTitle = 'Política de Privacidade';
$pageDescription = 'Versão ' . stridebr_privacy_version();
$pageHtml = '<p class="legal-lead"><strong>Última atualização: 9 de setembro de 2026.</strong> Esta Política explica quais dados o StrideBR trata, por que eles são necessários e quais controles o usuário possui.</p>
<h2>1. Dados da conta</h2><p>Podemos tratar nome, nome de exibição, username, e-mail, senha armazenada exclusivamente como hash, telefone quando informado, data de nascimento, foto de perfil, bio, esportes, preferências, configurações de privacidade e preferências de interface.</p>
<h2>2. Dados esportivos</h2><p>O StrideBR armazena os dados que você registra para usar o produto: cronogramas, exercícios, sessões, atividades, duração, distância, elevação, esforço percebido, equipamentos, metas, observações e demais campos escolhidos para cada modalidade. Ao importar FIT, TCX ou GPX, ou sincronizar uma conexão autorizada pelo usuário, também podem ser armazenados rota GPS, séries temporais, dados de sensores, identificador externo da atividade, origem e metadados do dispositivo disponibilizados pelo serviço. O arquivo original pode ser preservado quando o tamanho permitir.</p>
<h2>3. Rotas, localização e trechos privados</h2><p>Atividades compatíveis podem armazenar coordenadas de uma rota desenhada, importada ou gravada com o GPS Web. Quando uma modalidade possui trechos, tiros, voltas ou tentativas, cada unidade também pode ter um traçado próprio. Ao iniciar uma gravação GPS no navegador, o aparelho solicita permissão de localização e o StrideBR pode receber coordenadas, precisão estimada, horário, altitude e velocidade quando esses valores forem disponibilizados pelo dispositivo. Durante uma gravação ainda não enviada, o estado pode ser mantido localmente no navegador para reduzir perda de dados em caso de internet instável ou recarregamento.</p><p>GPS Web é uma estimativa e não possui as mesmas garantias de uma aplicação nativa em segundo plano: qualidade do sensor, economia de bateria, bloqueio da tela, troca de aplicativo/aba e políticas do navegador podem atrasar ou interromper atualizações. O StrideBR tenta filtrar ruído e saltos improváveis, registra indicadores de qualidade e permite revisar ou corrigir os dados antes e depois de salvar. O usuário não deve interpretar a precisão exibida pelo aparelho como garantia de exatidão.</p><p>Uma rota pode revelar locais sensíveis. O usuário pode configurar uma distância opcional para ocultar o início e o fim da rota nas representações destinadas a compartilhamento. A rota original permanece disponível de forma privada para o próprio registro; a configuração controla a versão compartilhável e pode ser alterada por atividade. O compartilhamento pode ser feito sem rota mesmo quando existe um traçado, e exportações visuais de rota aplicam as mesmas regras de ocultação.</p>
<h2>4. Serviços de mapa e elevação</h2><p>O mapa usa dados do OpenStreetMap. Para estimar a elevação do terreno, o StrideBR pode enviar uma amostra das coordenadas da rota ao serviço de elevação configurado, como Open-Meteo. Esses serviços recebem as informações técnicas necessárias para atender à solicitação conforme suas próprias políticas. A falha do serviço de elevação não precisa impedir o registro da atividade.</p>
<h2>5. Social, compartilhamento e treinador</h2><p>Solicitações de amizade, relações aceitas, compartilhamentos de cronograma e vínculos treinador-atleta são armazenados para entregar as funções escolhidas pelo usuário. Um compartilhamento pode ser uma cópia estática ou um acesso sincronizado em modo leitura ao cronograma original. No vínculo treinador-atleta, permissões específicas controlam quais áreas podem ser visualizadas ou usadas para prescrição.</p>
<h2>6. Notificações</h2><p>O StrideBR pode guardar notificações internas relacionadas a solicitações, convites, alterações de cronogramas sincronizados, vínculos e outras ações relevantes. A central registra o estado de leitura e pode conter um link para o contexto relacionado.</p>
<h2>7. Analytics de produto</h2><p>Se a opção estiver habilitada na conta, o StrideBR pode registrar eventos limitados de produto para entender fluxo, uso e desempenho. O sistema aceita apenas um conjunto restrito de nomes e valores estruturais e não deve incluir rota GPS, notas, cargas, nomes de exercícios ou conteúdo pessoal livre. Essa coleta pode ser desativada nas preferências.</p>
<h2>8. Aquisição e campanhas</h2><p>Para entender quais campanhas realmente trazem novos usuários, o StrideBR pode registrar de forma first-party a origem explícita de uma entrada, como um QR Code do próprio domínio ou parâmetros UTM. Essa atribuição usa um identificador aleatório no navegador; o servidor guarda sua forma transformada em hash junto de campanha, placement/origem e UTMs limitadas. Também podem ser registrados eventos mínimos de funil, como entrada, início e conclusão de cadastro e primeira atividade salva. Essa infraestrutura não usa fingerprinting, não armazena IP bruto, localização precisa ou user-agent completo para marketing e não envia dados esportivos a plataformas de anúncios.</p><p>Quando uma conta é criada a partir de uma origem conhecida, a atribuição inicial pode ser vinculada à conta para medir conversão de forma agregada. A origem inicial conhecida não é substituída por campanhas posteriores. Ao excluir a conta, o vínculo de usuário é removido das tabelas de atribuição conforme as relações do banco, podendo permanecer somente informação agregável da campanha sem identificar a conta.</p>
<h2>9. Eventos salvos</h2><p>Quando você salva um evento esportivo, o StrideBR registra a relação entre sua conta e o evento para que ele apareça na sua lista. Informações públicas do evento são mantidas separadamente do seu perfil.</p>
<h2>10. Segurança e operação</h2><p>Podemos tratar horário de cadastro e login, IP, user-agent, registros de acesso e identificadores transformados em hash quando necessários para limitar abuso, proteger autenticação, investigar erros e administrar o serviço. O acesso administrativo a dados técnicos é restrito por função.</p>
<h2>11. Feedback</h2><p>Feedback pode incluir texto, categoria e página de contexto. Se o envio for anônimo, ele não fica vinculado à sua conta e não é necessário registrar IP ou user-agent para esse feedback. Feedback já usado para corrigir o produto pode ser preservado sem vínculo com a conta após uma exclusão.</p>
<h2>12. Finalidades</h2><p>Usamos dados para autenticar usuários, entregar as funções do produto, calcular progresso, manter preferências, permitir compartilhamentos solicitados, oferecer suporte, prevenir abuso, manter segurança, diagnosticar falhas e melhorar o StrideBR.</p>
<h2>13. Visibilidade, publicidade e padrões de privacidade</h2><p>Perfis, cronogramas e atividades podem possuir controles como privado, amigos e público quando a funcionalidade correspondente está disponível. O usuário pode definir padrões para novas atividades e sobrescrevê-los individualmente. O StrideBR não vende dados pessoais a anunciantes e não exige um feed público para o funcionamento básico do produto.</p><p>Se publicidade for ativada para ajudar a financiar o serviço, ela fica restrita a páginas públicas sem dados do atleta e depende dos controles de consentimento aplicáveis. Dados esportivos, dados de saúde e informações recebidas de conexões como Fitbit, Garmin, Polar ou serviços equivalentes não são usados para segmentar publicidade.</p>
<h2>14. Fornecedores técnicos e conexões</h2><p>Hospedagem, e-mail transacional, mapas e serviços de elevação podem processar dados técnicos necessários para operar suas respectivas funções. Apenas os dados necessários para cada integração devem ser enviados.</p><p>Quando você conecta voluntariamente um serviço esportivo, como Garmin Connect, Strava, Polar Flow ou Fitbit, o StrideBR pode armazenar identificadores da conexão, escopos autorizados, horários de sincronização e credenciais de acesso protegidas para importar ou enviar os dados que você autorizou. Você pode desconectar o serviço nas configurações. Integrações móveis, como Health Connect, Samsung Health e Apple Health, dependem das permissões fornecidas no sistema operacional e no aplicativo correspondente.</p>
<h2>15. Senhas e tokens</h2><p>Senhas são protegidas por função de hash própria para senhas. Tokens de verificação de e-mail e recuperação de senha, quando usados, são aleatórios, expiram e têm uso controlado; o valor original do token não precisa ser armazenado no banco.</p>
<h2>16. Seus controles</h2><p>Você pode editar informações do perfil, escolher visibilidade, ajustar padrões de privacidade, desativar analytics de produto, gerenciar conexões e acessar a área “Seus dados” nas configurações. Essa área permite gerar uma exportação dos principais registros e iniciar a exclusão da conta com confirmação de senha.</p>
<h2>17. Exportação</h2><p>A exportação da conta gera um arquivo JSON com dados associados à conta, como perfil, cronogramas, atividades, unidades/trechos, rotas gerais e rotas por trecho, metas e equipamentos. Senha, tokens e informações de segurança como IPs não são incluídos. Atividades removidas que ainda estejam no período técnico de restauração podem aparecer na exportação completa da conta. Atividades individuais também podem ser exportadas em formatos compatíveis, como GPX, TCX e JSON.</p>
<h2>18. Exclusão, restauração e retenção</h2><p>Atividades removidas podem permanecer marcadas como excluídas por até 30 minutos para permitir a função Desfazer; durante esse período elas deixam de aparecer nos fluxos normais. A exclusão da conta remove os dados associados conforme as relações do banco. Alguns registros administrativos, de segurança ou feedback podem ser preservados sem o identificador da conta quando necessário para integridade, prevenção de abuso ou histórico do produto.</p>
<h2>19. Crianças e adolescentes</h2><p>O StrideBR procura aplicar minimização de dados e controles de privacidade adequados também para usuários mais jovens. Se a legislação aplicável exigir participação de um responsável, essa condição deve ser respeitada.</p>
<h2>20. Mudanças</h2><p>A versão aceita da Política pode ser registrada na conta. Mudanças relevantes podem gerar novo aviso e novo aceite.</p>
<h2>21. Contato</h2><p>Para solicitações relacionadas a privacidade ou dados pessoais, use <a href="'.stridebr_e(stridebr_support_mailto('Privacidade - StrideBR')).'">'.stridebr_e(stridebr_support_email()).'</a>. Não envie senha ou token de autenticação por e-mail.</p>';
require dirname(__DIR__, 3) . '/src/layout/static_page.php';
