<?php

declare(strict_types=1);
require_once dirname(__DIR__, 3) . '/src/includes/app.php';
$pageTitle = 'Termos de Uso';
$pageDescription = 'Versão ' . stridebr_terms_version();
$pageHtml = '<p class="legal-lead"><strong>Última atualização: 30 de agosto de 2026.</strong> Estes Termos regulam o uso do StrideBR. Ao criar ou continuar usando uma conta, você concorda com estes Termos e com a Política de Privacidade vigente.</p>
<h2>1. O que é o StrideBR</h2><p>O StrideBR é uma plataforma para planejar treinos, registrar e comparar atividades físicas, acompanhar progresso e metas, organizar exercícios, consultar eventos esportivos e usar recursos de colaboração como amigos, cronogramas compartilhados e vínculo treinador-atleta. Recursos podem evoluir conforme o produto é desenvolvido.</p>
<h2>2. Conta e segurança</h2><p>Você é responsável por manter sua senha protegida e por não usar a conta de outra pessoa sem autorização. O StrideBR pode limitar, bloquear ou encerrar contas quando houver tentativa de acesso indevido, fraude, abuso, automação maliciosa, assédio, violação destes Termos ou risco para outros usuários e para a infraestrutura.</p>
<h2>3. Idade e uso responsável</h2><p>Se a legislação aplicável exigir participação ou autorização de responsável para o seu uso do serviço, essa condição deve ser respeitada. O StrideBR procura reduzir exposição desnecessária de dados e oferece controles de privacidade, mas o usuário também deve avaliar o que decide tornar público.</p>
<h2>4. Treinos, saúde e desempenho</h2><p>O StrideBR é uma ferramenta de organização e registro esportivo. Ele não substitui avaliação médica, fisioterapêutica, nutricional, orientação profissional ou atendimento de emergência. Métricas calculadas pelo sistema, incluindo calorias, ritmo, distância, elevação e comparações, podem conter imprecisões e não devem ser tratadas como diagnóstico nem como definição automática de um treino "melhor" ou "pior".</p>
<h2>5. Conteúdo do usuário</h2><p>Você continua responsável por cronogramas, exercícios personalizados, observações, imagens, links e outros conteúdos que enviar. Não publique conteúdo ilegal, enganoso, ofensivo, invasivo, malicioso ou que viole direitos de terceiros. Não use campos livres para armazenar senhas, documentos sigilosos ou dados de terceiros sem necessidade e autorização.</p>
<h2>6. Perfis, amizades e compartilhamento</h2><p>Perfis, atividades e cronogramas podem possuir níveis de visibilidade. Um cronograma pode ser compartilhado como cópia independente ou, quando o recurso estiver disponível, em modo sincronizado de leitura: nesse caso o destinatário acompanha a versão atual do cronograma original e pode receber notificações quando o proprietário o altera. O proprietário pode encerrar esse acesso. O usuário deve conferir a visibilidade antes de publicar informações.</p>
<h2>7. Treinador e atleta</h2><p>O modo treinador cria um vínculo funcional para planejamento e acompanhamento conforme permissões concedidas pelo atleta. Ele não concede controle administrativo sobre a conta. O treinador também pode usar normalmente o StrideBR para seus próprios treinos. Qualquer orientação recebida pela plataforma continua sujeita às responsabilidades profissionais e de segurança aplicáveis fora do StrideBR.</p>
<h2>8. Rotas e localização</h2><p>Rotas podem revelar locais frequentados pelo usuário. A atividade inteira e seus trechos/tentativas podem possuir traçados próprios quando a modalidade permitir. O StrideBR permite manter a rota original da atividade e, para compartilhamento, ocultar opcionalmente trechos do início e do fim. Essa ocultação não altera os dados privados originais. A rota é opcional no cartão mesmo quando existe no registro.</p><p>A gravação GPS feita pelo site depende das APIs, sensores e políticas do navegador e do aparelho. Ela é uma estimativa: pode apresentar pontos atrasados, saltos, lacunas, distância, ritmo ou elevação imprecisos e não promete rastreamento contínuo quando a página está em segundo plano ou a tela é bloqueada. O StrideBR aplica filtros de qualidade e tenta preservar a gravação localmente, mas o usuário deve revisar o resultado e pode editar os dados quando necessário.</p>
<h2>9. Eventos esportivos</h2><p>O StrideBR pode organizar informações obtidas de sites oficiais, organizadores e outras fontes identificadas. Salvo quando informado de forma expressa, o StrideBR não é organizador do evento. Datas, preços, percursos, regulamentos e disponibilidade de inscrição devem ser confirmados na fonte oficial antes da participação.</p>
<h2>10. Importação e exportação de atividades</h2><p>O StrideBR pode ler arquivos esportivos como FIT, TCX e GPX e tentar converter os dados para o modelo interno da plataforma. Arquivos produzidos por relógios, aplicativos e serviços diferentes podem conter campos proprietários, ausentes ou incompatíveis; por isso, a importação e a exportação podem não reproduzir todos os dados exatamente. O usuário continua responsável por manter cópias dos arquivos originais que considere importantes.</p>
<h2>11. Exclusão, restauração e desfazer</h2><p>Algumas ações reversíveis podem oferecer um período curto de "Desfazer". Uma atividade removida pode permanecer marcada como excluída por um período limitado para permitir restauração antes de deixar de aparecer nas áreas normais do produto. A exclusão da conta é um fluxo separado, exige confirmação e possui consequências mais amplas.</p>
<h2>12. Notificações</h2><p>O StrideBR pode exibir notificações relacionadas a ações úteis do produto, como convites, alterações em cronogramas sincronizados, vínculos e outras mudanças que exigem informação ou ação. O objetivo não é usar notificações para pressionar o usuário a treinar ou manter pontuações artificiais.</p>
<h2>13. Analytics de produto</h2><p>Quando habilitado nas preferências, o StrideBR pode registrar eventos técnicos e de fluxo para entender uso e desempenho, como conclusão de onboarding ou uso de uma funcionalidade. Esse mecanismo é limitado a dados estruturais permitidos e não deve registrar rota GPS, notas, cargas, conteúdo de exercícios ou outros conteúdos pessoais livres.</p>
<h2>14. Disponibilidade</h2><p>O serviço pode passar por manutenção, falhas de infraestrutura ou mudanças de funcionalidade. Embora existam medidas de backup e segurança, nenhum serviço online deve ser o único local de armazenamento de informação insubstituível. O recurso de exportação de dados pode ser usado para manter uma cópia dos seus registros.</p>
<h2>15. Administração e moderação</h2><p>Moderadores, administradores e o proprietário podem agir sobre contas, conteúdo e configurações quando necessário para suporte, segurança, prevenção de abuso, cumprimento destes Termos e operação do serviço. Ações administrativas sensíveis podem ser registradas em log interno.</p>
<h2>16. Código e propriedade</h2><p>O código-fonte público do projeto segue a licença indicada no repositório. Ter acesso ao código não concede acesso a contas, banco de dados, infraestrutura, segredos de operação ou dados privados de usuários.</p>
<h2>17. Exclusão da conta</h2><p>Usuários podem usar os controles disponíveis para exportar dados e solicitar a exclusão da própria conta. A exclusão pode manter apenas registros que precisem ser preservados de forma desvinculada para segurança, histórico de feedback, obrigações aplicáveis ou integridade administrativa.</p>
<h2>18. Alterações destes Termos</h2><p>A versão aceita pode ser registrada na conta. Mudanças relevantes podem exigir novo aceite antes da continuação do uso.</p>
<h2>19. Contato</h2><p>Dúvidas de conta, privacidade ou uso podem ser enviadas para <a href="'.stridebr_e(stridebr_support_mailto('Termos de Uso - StrideBR')).'">'.stridebr_e(stridebr_support_email()).'</a> ou pelos canais indicados na página de Suporte.</p>';
require dirname(__DIR__, 3) . '/src/layout/static_page.php';
