<?php
$pageTitle = 'Atualizações';
$pageDescription = 'Principais mudanças do StrideBR em linguagem de produto.';
$pageHtml = '<div class="changelog-list">
<section><time>30 de agosto de 2026</time><h2>Compartilhamento v2 e treinos intervalados</h2><ul><li>Atividades passam a ser compartilháveis mesmo sem rota.</li><li>Quando existe traçado, <strong>Exibir rota?</strong> permite escolher se ele entra no card sem alterar o registro original.</li><li>Cards podem ser copiados como imagem e o traçado pode ser exportado separadamente em PNG transparente.</li><li>Trechos, tiros, voltas e tentativas podem armazenar uma rota própria e ser compartilhados juntos ou em imagens separadas.</li><li>No mobile web, a personalização do compartilhamento usa um bottom sheet para manter a prévia em foco.</li></ul></section>
<section><time>30 de agosto de 2026</time><h2>Preparação da Release Candidate</h2><ul><li>Home passa a priorizar o contexto de hoje e permite reorganizar módulos secundários.</li><li>Nova área de Progresso com consistência, tendências e marcas pessoais.</li><li>Comparação A/B de atividades com seleção padrão da última atividade do mesmo esporte e sugestões relacionadas.</li><li>Atividades ganham privacidade padrão, ocultação opcional do início/fim da rota em compartilhamentos e exclusão reversível com Desfazer.</li><li>Cronogramas sincronizados em modo leitura passam a acompanhar o original e avisar sobre alterações relevantes.</li><li>Central de notificações, painel de treinador ampliado e controles de analytics de produto.</li><li>Proteções contra envios duplicados são reforçadas no navegador e no servidor.</li><li>Landing, onboarding, páginas públicas e documentos legais foram revisados para a 1.0 RC.</li></ul></section>
<section><time>26 de agosto de 2026</time><h2>Pré-release e hardening</h2><ul><li>Diagnóstico administrativo compara ambiente, banco, migrations, e-mail, uploads, extensões PHP e feature flags antes da publicação.</li><li>Formulários ganham proteção visual contra envios duplicados e aviso quando o navegador fica offline.</li><li>Erros internos em produção recebem uma referência curta para localizar o evento correspondente nos logs sem expor detalhes técnicos.</li><li>Imagens de eventos passam por otimização para WebP e redimensionamento quando o servidor possui suporte, economizando armazenamento.</li><li>Estados vazios de cronogramas, perfil e treinador ganharam próximos passos mais claros.</li><li>A verificação estática agora detecta formulários aninhados e confere proteções essenciais de Apache/uploads.</li></ul></section>
<section><time>25 de agosto de 2026</time><h2>Melhorias para uso diário</h2><ul><li>Repetição de atividades com preenchimento baseado no registro anterior.</li><li>Rascunhos locais para formulários de atividades e cronogramas.</li><li>Resumo pós-treino e histórico rápido dos exercícios durante a execução.</li><li>Conta e segurança ampliadas com troca confirmada de e-mail e gerenciamento de sessões.</li><li>Importação administrativa de eventos por JSON ou CSV com prévia e detecção de duplicados.</li><li>Relatos de problema podem anexar contexto técnico básico, sem dados sensíveis.</li><li>Identificação de versão e build no rodapé para facilitar testes.</li></ul></section>
<section><time>25 de agosto de 2026</time><h2>Rotas, compartilhamento e acabamento do produto</h2><ul><li>Rotas desenhadas em mapa para modalidades compatíveis, com distância calculada no servidor.</li><li>Estimativa de elevação do terreno e perfil de elevação para atividades com rota.</li><li>Cards de atividade para compartilhamento com identidade visual do StrideBR.</li><li>Metas ampliadas com progresso automático, objetivos sem prazo ou com data limite, dias ativos, edição e histórico de conclusões.</li><li>Primeira versão funcional de Eventos, com fontes, imagens, filtros e eventos salvos.</li><li>Exportação de dados e fluxo de exclusão da própria conta.</li><li>Revisão de páginas públicas, suporte, documentos legais, SEO e páginas de erro.</li><li>Recuperação de senha e confirmação de e-mail preparadas para a versão pública.</li><li>Polimento da agenda mensal, dashboard e ferramentas rápidas em desktop e mobile.</li><li>Rodada de estabilização com testes adicionais de atividades, cronogramas, rotas, amigos, compartilhamento, treinador e permissões.</li></ul></section>
<section><time>24 de agosto de 2026</time><h2>Execução e registro de treino</h2><ul><li>Sessões de treino ligadas ao cronograma.</li><li>Conclusão de sessão gerando registro de atividade.</li><li>Melhorias de consistência na execução e proteção contra conclusões duplicadas.</li></ul></section>
<section><time>22 de agosto de 2026</time><h2>Atividades v2, metas e equipamentos</h2><ul><li>Catálogo de modalidades com busca, favoritos e campos específicos.</li><li>Melhorias no registro de duração, esforço, equipamentos e métricas.</li><li>Dashboard com resumo semanal, atividades recentes e metas.</li></ul></section>
<section><time>19 de agosto de 2026</time><h2>Agenda e treinador</h2><ul><li>Agenda mensal com recorrências e treinos por data.</li><li>Vínculo treinador-atleta com permissões, prescrições e acompanhamento básico.</li><li>Reforços de autenticação, rate limiting, HTTPS, sessão e identidade.</li></ul></section>
</div><p>O histórico técnico completo continua disponível nos commits do repositório.</p>';
require dirname(__DIR__, 3) . '/src/layout/static_page.php';
