expose_php=Off
log_errors=On
error_log=/proc/self/fd/2
display_errors=Off
session.use_strict_mode=1
session.use_only_cookies=1
session.cookie_httponly=1
session.cookie_samesite=Lax
session.save_path=/tmp
upload_tmp_dir=/tmp
auto_prepend_file=/var/www/html/src/includes/errors.php
