const fs = require('fs')
const vm = require('vm')
const path = require('path')
const root = path.resolve(__dirname, '..', '..')
const source = fs.readFileSync(path.join(root, 'public/assets/js/activity-route-utils.js'), 'utf8')
const context = {window:{}, console}
vm.createContext(context)
vm.runInContext(source, context)
const R = context.window.StrideBRRoute
let assertions = 0
const ok = (condition, message) => { assertions += 1; if (!condition) throw new Error(message) }
const near = (a,b,tolerance,message) => ok(Math.abs(a-b) <= tolerance, `${message}: ${a} vs ${b}`)

const baseOpen = [[-53.3900,-27.3600],[-53.3890,-27.3600],[-53.3890,-27.3610],[-53.3900,-27.3610]]
const free = R.geojson(baseOpen)
ok(free?.type === 'LineString' && free.coordinates.length === 4, 'rota livre continua LineString normal')
const closed = R.closeCircuit(baseOpen)
ok(closed.length === 5 && R.samePoint(closed[0], closed.at(-1)), 'circuito fecha o último ponto no primeiro')
const baseDistance = R.distanceMeters(closed)
ok(baseDistance > 350 && baseDistance < 500, 'distância da volta-base plausível')
const one = R.expandCircuit(baseOpen, 1)
ok(one.ok && one.coordinates.length === 5, 'uma volta expande corretamente')
const ten = R.expandCircuit(baseOpen, 10)
ok(ten.ok && ten.laps === 10 && ten.coordinates.length === 41, 'dez voltas expandem sem duplicar junções')
near(R.distanceMeters(ten.coordinates), baseDistance * 10, 0.05, 'distância total é N vezes a base')
ok(R.samePoint(ten.coordinates[0], ten.coordinates.at(-1)), 'geometria repetida termina no início')
for (let lap=1; lap<=10; lap += 1) ok(R.samePoint(ten.coordinates[lap * 4], closed[0]), `volta ${lap} conecta no início`)
const detected = R.detectCircuit(ten.coordinates)
ok(detected?.laps === 10 && detected.base.length === 5, 'atividade reaberta recupera volta-base e quantidade')
const crossingBase = [[0,0],[0.001,0],[0.001,0.001],[0,0],[0.002,0],[0.002,0.002]]
const crossing = R.expandCircuit(crossingBase, 3)
const crossingDetected = R.detectCircuit(crossing.coordinates)
ok(crossingDetected?.laps === 3 && crossingDetected.base.length === 7, 'detecção tenta fechamentos posteriores quando a volta-base cruza o início no meio')
const changedBase = baseOpen.map((p,i) => i === 1 ? [p[0]+0.0002,p[1]] : p)
const changed = R.expandCircuit(changedBase, 10)
ok(changed.ok && Math.abs(R.distanceMeters(changed.coordinates) - R.distanceMeters(ten.coordinates)) > 1, 'editar base regenera repetições')
const changedLaps = R.expandCircuit(baseOpen, 3)
ok(changedLaps.ok && changedLaps.coordinates.length === 13, 'alterar quantidade regenera rota')
const tooDetailed = Array.from({length:251}, (_,i) => [-53.39 + (i%50)*0.00001, -27.36 + Math.floor(i/50)*0.00001])
const limited = R.expandCircuit(tooDetailed, 10)
ok(!limited.ok && limited.reason === 'point_limit' && limited.pointCount > R.MAX_POINTS, 'limite de pontos bloqueia sem truncar')
ok(R.geojson(ten.coordinates)?.coordinates.length === ten.coordinates.length, 'GeoJSON final contém atividade completa')
ok(R.detectCircuit(baseOpen) === null, 'rota aberta não é confundida com circuito')
ok(R.detectCircuit(closed) === null, 'circuito de uma volta não reclassifica automaticamente uma rota livre fechada')
console.log(`✓ activity route circuit: ${assertions} assertions`)
