const fs = require('fs')
const js = fs.readFileSync('public/assets/js/atividades.js', 'utf8')
const html = fs.readFileSync('public/user/atividades.php', 'utf8')
let assertions = 0
const check = (condition, message) => { assertions += 1; if (!condition) throw new Error(message) }
check(js.includes('storyWidth: 19.5'), 'espessura story padrão não foi reforçada')
check(js.includes('standardWidth: 15'), 'espessura padrão não foi reforçada')
check(js.includes("const selectedRouteExportColor = () =>"), 'cor da exportação não está centralizada')
check(js.includes('const selectedRouteExportWidth = () =>'), 'espessura da exportação não está centralizada')
check(js.includes('routeExportWidthScale = canvasWidth'), 'preview/export não compartilham escala proporcional ao canvas')
check(js.includes('drawRouteExportSurface(shareRouteExportPreview)'), 'preview não usa o mesmo renderer da exportação')
check(js.includes('const resolveShareRouteVisualStyle ='), 'preview/card/export não compartilham definição visual da rota')
check(js.includes('const shareRouteColorWithAlpha ='), 'glow customizado não usa a cor da rota de forma compartilhada')
const exportSurfaceStart = js.indexOf('    const drawRouteExportSurface =')
const exportSurfaceEnd = js.indexOf('    const syncRouteExportPreview =', exportSurfaceStart)
const exportSurface = js.slice(exportSurfaceStart, exportSurfaceEnd)
check(!exportSurface.includes('coreColor: color'), 'export ainda apaga a linha clara interna usando a mesma cor da rota')
check(!exportSurface.includes('shadowColor:'), 'export ainda mantém shadow/glow divergente do renderer compartilhado')
check(js.includes('if (!drawRouteExportSurface(canvas)) return'), 'PNG final não usa o mesmo renderer da preview')
check(js.includes('shareExportRouteButton?.addEventListener(\'click\', openRouteExportSheet)'), 'clique ainda exporta direto')
check(html.includes('data-route-export-sheet hidden'), 'popup de exportação não existe')
check(html.includes('data-route-export-color'), 'popup não oferece cor')
check(html.includes('min="55" max="180"') && html.includes('data-route-export-width'), 'popup não oferece espessura')
check(html.includes('data-route-export-preview'), 'popup não oferece preview')
check(html.includes('data-route-export-confirm'), 'popup não oferece ação explícita de exportar')
check(js.includes('shareRouteCoordinateCache = new WeakMap()'), 'geometria compartilhável não está memoizada')
check(js.includes('shareSegmentDataCache = new WeakMap()'), 'dados derivados de trechos não estão memoizados')
check(js.includes('const routeBox={x:stage.x+26,y:y+18,width:stage.width*.57,height:rowH-36}') && js.includes('widthScale:.72'), 'renderer por trecho não preserva uma área de rota legível')
check(js.includes('sharePresetPreviewFingerprint'), 'mini previews não têm fingerprint de cache')
check(js.includes('requestIdleCallback'), 'mini previews não foram retiradas do caminho crítico')
const scheduleStart = js.indexOf('function scheduleShareDraw()')
const scheduleEnd = js.indexOf('const setSharePhoto =', scheduleStart)
const schedule = js.slice(scheduleStart, scheduleEnd)
check(!schedule.includes('.then(() => renderSharePresetPreviews())'), 'draw principal ainda espera mini previews serialmente')
check(schedule.includes('shareRenderPromise.then(scheduleSharePresetPreviews)'), 'mini previews não são agendadas depois da principal')
console.log(`✓ share route PNG/export performance: ${assertions} assertions`)
