<?php
return function (PDO $pdo): void {
    $trainer = alphaTestUser($pdo, 'trainer_a', ['trainer' => true]);
    $athlete = alphaTestUser($pdo, 'trainer_b');
    $intruder = alphaTestUser($pdo, 'trainer_c');
    $link = treinadorCriarConvite($pdo, $trainer, 'alpha_trainer_b', 'treinador');
    AlphaTest::throws(fn() => treinadorResponderVinculo($pdo, $intruder, $link, 'aceitar'), 'Terceiro aceitou vínculo alheio');
    treinadorResponderVinculo($pdo, $athlete, $link, 'aceitar');
    AlphaTest::assert(treinadorVinculoAceito($pdo, $trainer, $athlete) !== [], 'Vínculo não foi aceito');
    treinadorAtualizarPermissoes($pdo, $athlete, $link, ['pode_prescrever' => '1']);
    AlphaTest::throws(fn() => treinadorAtualizarPermissoes($pdo, $intruder, $link, ['pode_prescrever' => '1']), 'Terceiro mudou permissões do atleta');
    $date = (new DateTimeImmutable('tomorrow'))->format('Y-m-d');
    $payload = ['titulo'=>'Treino com conteúdo livre', 'data_treino'=>$date, 'status'=>'rascunho'];
    $draft = treinadorCriarPrescricao($pdo, $trainer, $athlete, $payload, [['nome'=>'Agachamento', 'series'=>3]]);
    AlphaTest::throws(fn() => treinadorPublicarPrescricao($pdo, $intruder, $draft), 'Terceiro publicou prescrição');
    treinadorPublicarPrescricao($pdo, $trainer, $draft);
    AlphaTest::throws(fn() => treinadorSalvarFeedback($pdo, $athlete, $draft, 4, 'Ainda não concluído'), 'Feedback em treino não concluído');
    $pdo->prepare("UPDATE treinos_agendados SET status='concluido' WHERE idagendamento=:id")->execute([':id'=>$draft]);
    treinadorSalvarFeedback($pdo, $athlete, $draft, 4, 'Comentário livre em português');
    AlphaTest::throws(fn() => treinadorSalvarFeedback($pdo, $intruder, $draft, 1, 'IDOR'), 'Terceiro alterou feedback');
    $feedback = $pdo->prepare('SELECT feedback_atleta FROM treinos_agendados WHERE idagendamento=:id');
    $feedback->execute([':id'=>$draft]);
    AlphaTest::same('Comentário livre em português', $feedback->fetchColumn(), 'Conteúdo livre alterado');
    treinadorAtualizarPermissoes($pdo, $athlete, $link, []);
    AlphaTest::throws(fn() => treinadorCriarPrescricao($pdo, $trainer, $athlete, $payload, []), 'Criou prescrição sem permissão');
    $secondAthlete = alphaTestUser($pdo, 'trainer_second');
    AlphaTest::same([], treinadorVinculoAceito($pdo, $trainer, $secondAthlete), 'Segundo atleta herdou vínculo');
    $secondLink = treinadorCriarConvite($pdo, $trainer, 'alpha_trainer_second', 'treinador');
    AlphaTest::same([], treinadorVinculoAceito($pdo, $trainer, $secondAthlete), 'Convite pendente liberou dados');
    treinadorResponderVinculo($pdo, $secondAthlete, $secondLink, 'aceitar');
    AlphaTest::assert(treinadorVinculoAceito($pdo, $trainer, $secondAthlete) !== [], 'Segundo atleta não ficou independente');
    treinadorEncerrarVinculo($pdo, $athlete, $link);
    AlphaTest::same([], treinadorVinculoAceito($pdo, $trainer, $athlete), 'Vínculo encerrado continuou autorizado');
};
