const fs = require('fs')
const path = require('path')
const root = path.resolve(__dirname, '..', '..')
const builder = fs.readFileSync(path.join(root, 'public/assets/js/workout-builder.js'), 'utf8')
const session = fs.readFileSync(path.join(root, 'public/assets/js/workout-session.js'), 'utf8')
const preview = fs.readFileSync(path.join(root, 'public/assets/js/cronogramas.js'), 'utf8')
const css = fs.readFileSync(path.join(root, 'public/assets/css/cronogramas.css'), 'utf8')
let assertions = 0
const ok = (value, message) => { assertions++; if (!value) throw new Error(message) }
ok(builder.includes('StrideBRWorkoutBuilder = {serialize: formRows, hydrate: hydrateRows, setDirty}'), 'Shared Builder serialize API missing')
ok(builder.includes('hydrate: hydrateRows'), 'Shared Builder hydrate API missing')
ok(builder.includes('createGroupFromCards'), 'Shared group factory missing')
ok(session.includes('renderGroupFromSequence'), 'Session group sequence renderer missing')
ok(session.includes('round.members'), 'Session renderer does not iterate group members by round')
ok(session.includes('round.rest_between_exercises_s'), 'Session renderer ignores between-exercise rest')
ok(session.includes('round.rest_after_round_s'), 'Session renderer ignores after-round rest')
ok(preview.includes('renderPresentationItems'), 'Preview does not render canonical presentation')
ok(preview.includes('data-quick-complete-mode'), 'Preview does not carry quick-complete classification')
ok(preview.includes('data-quick-register-ambiguous'), 'Ambiguous quick completion warning is not wired')
ok(preview.indexOf('data-start-workout') < preview.indexOf('data-quick-register-workout', preview.indexOf('const sessionActions')), 'Structured Start action is not primary before quick completion')
ok(css.includes('.wb-group-selector{display:flex;justify-content:center'), 'Mobile group selection control is hidden')
ok(builder.includes('[data-wb-move]'), 'Accessible reorder alternative regressed')
console.log(`Training Platform Consistency V1 JS: ${assertions} assertions`)
