<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/src/function/workout_session_service.php';
class WorkoutV2CountingPDO extends PDO { public int $catalogReads=0; public function prepare(string $query,array $options=[]):PDOStatement|false { if (preg_match('/\bFROM\s+exercicios\b/i',$query) === 1) ++$this->catalogReads; return parent::prepare($query,$options); } }
return function(PDO $pdo):void {
 $user=alphaTestUser($pdo,'execution_v2'); $other=alphaTestUser($pdo,'execution_v2_other');
 $schedule=cronogramaCriar($pdo,$user,'Execution V2');
 $workout=cronogramaSalvarTreino($pdo,$user,['idcronograma'=>$schedule,'titulo'=>'Treino C','dia_semana'=>1,'hora_inicio'=>'08:00','hora_fim'=>'09:00','idmodalidade'=>'m_musculacao']);
 $canonical=$pdo->query("SELECT idexercicio,nome FROM exercicios WHERE idusuario IS NULL AND ativo=TRUE AND nome='Supino reto' LIMIT 1")->fetch();
 AlphaTest::assert((bool)$canonical,'Real catalog supplies canonical fixture');
 $scott=stridebr_generate_id();$pdo->prepare("INSERT INTO exercicios(idexercicio,idusuario,nome,slug,ativo,visibilidade,status_publicacao) VALUES(?,?,'Rosca Scott',?,TRUE,'privado','privado')")->execute([$scott,$user,'scott-'.$scott]);
 $insert=$pdo->prepare('INSERT INTO treinos_exercicios(idtreino_exercicio,idtreino,idexercicio,nome_snapshot,series,repeticoes,carga,descanso,duracao,distancia,observacoes,ordem) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');
 $ids=array_map(static fn()=>stridebr_generate_id(),range(1,7));
 $insert->execute([$ids[0],$workout,$canonical['idexercicio'],'OLD LINKED NAME',4,'12','40 kg','90 s',null,null,'Keep notes',1]);
 $insert->execute([$ids[1],$workout,null,'SUPINO RETO',2,'8–12',null,'30 s',null,null,'Range',2]);
 $insert->execute([$ids[2],$workout,null,'Rosca scut',1,'12',null,null,null,null,'Fuzzy',3]);
 $insert->execute([$ids[3],$workout,null,'PUXADOR FRENT PR',1,null,null,null,'20 min','500 m','Unknown',4]);
 $insert->execute([$ids[4],$workout,null,'Aeróbico custom',3,null,null,null,'20 min','500 m',null,5]);
 $insert->execute([$ids[5],$workout,null,'Bodyweight custom',4,'12',null,null,null,null,null,6]);
 $insert->execute([$ids[6],$workout,null,'Load target custom',1,'12','10 kg',null,null,null,null,7]);
 $before=cronogramaPlanoNomes($pdo,$user,'workout',$workout)['rows'];
 $counting=new WorkoutV2CountingPDO((string)$GLOBALS['dsn'],(string)$GLOBALS['dbuser'],(string)$GLOBALS['dbpassword'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $counting->exec('SET search_path TO stridebr, public');cronogramaHidratarExerciciosPlanejados($counting,$user,$before);AlphaTest::assert($counting->catalogReads <= 1,'At most one catalog query for all planned rows');
 $display=cronogramaListarTreinoExercicios($pdo,$workout,$user);
 AlphaTest::same('Supino reto',$display[0]['nome_snapshot'],'Linked plan hydration uses current name');
 AlphaTest::same('Supino reto',$display[1]['nome_snapshot'],'ALL CAPS unlinked hydration canonical');
 AlphaTest::same('Rosca scut',$display[2]['nome_snapshot'],'Fuzzy plan never silently rewrites');
 AlphaTest::same('PUXADOR FRENT PR',$display[3]['nome_snapshot'],'Unknown abbreviations untouched');
 AlphaTest::same(2,cronogramaRepararNomesPlano($pdo,$user,'workout',$workout),'Safe bulk repairs only safe rows');
 $after=cronogramaPlanoNomes($pdo,$user,'workout',$workout)['rows'];
 foreach ($before as $i=>$row) { unset($row['idexercicio'],$row['nome_snapshot']);$actual=$after[$i];unset($actual['idexercicio'],$actual['nome_snapshot']);AlphaTest::same($row,$actual,'Safe repair changes only name/identity'); }
 AlphaTest::same('Rosca scut',$after[2]['nome_snapshot'],'Bulk skips fuzzy');
 AlphaTest::throws(fn()=>cronogramaRepararNomesPlano($pdo,$other,'workout',$workout),'Other user cannot repair plan');
 AlphaTest::same(0,cronogramaRepararNomesPlano($pdo,$user,'workout',$workout,'keep',$ids[2]),'Keep performs no rewrite');
 AlphaTest::same('Rosca scut',cronogramaPlanoNomes($pdo,$user,'workout',$workout)['rows'][2]['nome_snapshot'],'Keep preserves original');
 AlphaTest::same(1,cronogramaRepararNomesPlano($pdo,$user,'workout',$workout,'map',$ids[3],$scott),'Explicit library mapping allowed');
 $model=cronogramaSalvarTreinoModelo($pdo,$user,['titulo'=>'Model V2','idmodalidade'=>'m_musculacao']);
 $modelRow=stridebr_generate_id();$pdo->prepare("INSERT INTO treinos_modelo_exercicios(idtreino_modelo_exercicio,idtreino_modelo,nome_snapshot,series,ordem) VALUES(?,?,'SUPINO RETO',4,1)")->execute([$modelRow,$model]);
 AlphaTest::same('Supino reto',cronogramaBuscarTreinoModelo($pdo,$user,$model)['exercicios'][0]['nome_snapshot'],'Template uses shared hydration');
 AlphaTest::same(1,cronogramaRepararNomesPlano($pdo,$user,'template',$model),'Template safe repair');
 $session=sessaoIniciarCronograma($pdo,$user,$workout);$sessionId=$session['idsessao'];
 AlphaTest::same('Supino reto',$session['exercicios'][0]['nome_snapshot'],'New session canonical name');
 AlphaTest::throws(fn()=>$pdo->exec("UPDATE sessoes_treino_series SET duracao_realizada_s=-1 WHERE idsessao_exercicio='".$session['exercicios'][0]['idsessao_exercicio']."'"),'Duration constraint rejects negative');
 AlphaTest::throws(fn()=>$pdo->exec("UPDATE sessoes_treino_series SET distancia_realizada_m=-1 WHERE idsessao_exercicio='".$session['exercicios'][0]['idsessao_exercicio']."'"),'Distance constraint rejects negative');
 $exercise=$session['exercicios'][0];$sets=$exercise['series'];$defaults=[];
 $result=sessaoAtualizarSerie($pdo,$user,$sets[0]['idserie'],'13','',true,'reps',$defaults,$sessionId);$defaults=$result['field_defaults'];
 AlphaTest::same(['13','13','13','13'],array_column($result['session']['exercicios'][0]['series'],'repeticoes_realizadas'),'Reps #1 forward 13');
 $result=sessaoAtualizarSerie($pdo,$user,$sets[1]['idserie'],'4','',true,'reps',$defaults,$sessionId);$defaults=$result['field_defaults'];
 AlphaTest::same(['13','4','4','4'],array_column($result['session']['exercicios'][0]['series'],'repeticoes_realizadas'),'Reps #2 preserves #1');
 $result=sessaoAtualizarSerie($pdo,$user,$sets[0]['idserie'],'','40',true,'load',$defaults,$sessionId);$defaults=$result['field_defaults'];
 AlphaTest::same(['40 kg','40 kg','40 kg','40 kg'],array_column($result['session']['exercicios'][0]['series'],'carga_realizada'),'Load forward');
 $result=sessaoAtualizarSerie($pdo,$user,$sets[1]['idserie'],'','45',true,'load',$defaults,$sessionId);$defaults=$result['field_defaults'];
 AlphaTest::same(['40 kg','45 kg','45 kg','45 kg'],array_column($result['session']['exercicios'][0]['series'],'carga_realizada'),'Load #2 preserves #1');
 sessaoAlternarSerie($pdo,$user,$sets[2]['idserie'],true,$sessionId);
 $result=sessaoAtualizarSerie($pdo,$user,$sets[1]['idserie'],'5','',true,'reps',$defaults,$sessionId);$defaults=$result['field_defaults'];
 AlphaTest::same(['13','5','4','5'],array_column($result['session']['exercicios'][0]['series'],'repeticoes_realizadas'),'Completed later set not overwritten');
 AlphaTest::throws(fn()=>sessaoAtualizarSerie($pdo,$user,$sets[2]['idserie'],'9','',true,'reps',$defaults,$sessionId),'Completed source cannot change');
 $boundary=sessaoAtualizarSerie($pdo,$user,$sets[0]['idserie'],'14','',true,'reps',$defaults,$sessionId);
 AlphaTest::same(['14','5','4','5'],array_column($boundary['session']['exercicios'][0]['series'],'repeticoes_realizadas'),'Known manual boundary stops earlier source');
 $result=sessaoAtualizarSerie($pdo,$user,$sets[0]['idserie'],'99','',true,'reps',[],$sessionId);
 AlphaTest::same(['99','5','4','5'],array_column($result['session']['exercicios'][0]['series'],'repeticoes_realizadas'),'Lost provenance preserves stored actuals');
 $aerobic=$session['exercicios'][4]['series'];
 $result=sessaoAtualizarSerie($pdo,$user,$aerobic[0]['idserie'],'','',true,'duration',[],$sessionId,'25 min');$defaults=$result['field_defaults'];
 AlphaTest::same([1500,1500,1500],array_map('intval',array_column($result['session']['exercicios'][4]['series'],'duracao_realizada_s')),'Duration forward');
 $result=sessaoAtualizarSerie($pdo,$user,$aerobic[1]['idserie'],'','',true,'duration',$defaults,$sessionId,'01:30');$defaults=$result['field_defaults'];
 AlphaTest::same([1500,90,90],array_map('intval',array_column($result['session']['exercicios'][4]['series'],'duracao_realizada_s')),'Duration #2 forward only');
 $result=sessaoAtualizarSerie($pdo,$user,$aerobic[0]['idserie'],'','',true,'distance',$defaults,$sessionId,null,'1,5 km');$defaults=$result['field_defaults'];
 AlphaTest::same(['1500.000','1500.000','1500.000'],array_column($result['session']['exercicios'][4]['series'],'distancia_realizada_m'),'Distance forward');
 $result=sessaoAtualizarSerie($pdo,$user,$aerobic[1]['idserie'],'','',true,'distance',$defaults,$sessionId,null,'500 m');
 AlphaTest::same(['1500.000','500.000','500.000'],array_column($result['session']['exercicios'][4]['series'],'distancia_realizada_m'),'Distance boundary per field');
 AlphaTest::throws(fn()=>sessaoAtualizarSerie($pdo,$user,$aerobic[0]['idserie'],'','',true,'duration',[],$sessionId,'bad'),'Invalid duration rejected');
 AlphaTest::assert(!$pdo->inTransaction(),'Invalid parser leaves no transaction');
 $defaultSet=sessaoAlternarSerie($pdo,$user,$session['exercicios'][6]['series'][0]['idserie'],true,$sessionId);
 AlphaTest::same(null,$defaultSet['exercicios'][6]['series'][0]['carga_realizada'],'Individual Done keeps unknown actual load null');
 sessaoAlternarExercicio($pdo,$user,$session['exercicios'][5]['idsessao_exercicio'],true,$sessionId);
 AlphaTest::same(null,sessaoCarregarPorId($pdo,$user,$sessionId)['exercicios'][5]['series'][0]['repeticoes_realizadas'],'Exercise Done keeps unknown actual reps null');
 sessaoMarcarTudo($pdo,$user,true,$sessionId);$done=sessaoCarregarPorId($pdo,$user,$sessionId);
 AlphaTest::same(null,$done['exercicios'][5]['series'][0]['repeticoes_realizadas'],'Done keeps unknown actual reps null');
 AlphaTest::same(null,$done['exercicios'][6]['series'][0]['carga_realizada'],'Done keeps unknown actual load null');
 AlphaTest::same(null,$done['exercicios'][5]['series'][0]['carga_realizada'],'Reps-only load optional, no zero');
 AlphaTest::same(null,$done['exercicios'][1]['series'][0]['repeticoes_realizadas'],'Done does not invent range actual');
 AlphaTest::same(null,$done['exercicios'][3]['series'][0]['duracao_realizada_s'],'Done keeps unknown actual duration null');
 AlphaTest::same(null,$done['exercicios'][3]['series'][0]['distancia_realizada_m'],'Done keeps unknown actual distance null');
 $metricBefore=sessaoCarregarPorId($pdo,$user,$sessionId,false)['exercicios'][4]['series'];
 $pdo->exec((string) file_get_contents(dirname(__DIR__,2).'/src/database/migrations/20260918_workout_session_actual_metrics_v1.sql'));
 AlphaTest::same($metricBefore,sessaoCarregarPorId($pdo,$user,$sessionId,false)['exercicios'][4]['series'],'Rerun additive migration preserves existing actual metrics');
 $finish=sessaoFinalizar($pdo,$user,$sessionId,['inicio_real'=>'2026-09-18 08:00','fim_real'=>'2026-09-18 09:00']);
 $query=$pdo->prepare('SELECT carga_kg,repeticoes,duracao_segundos,distancia_metros FROM series_exercicio_atividade WHERE idregistro=? ORDER BY ordem_exercicio,ordem_serie');$query->execute([$finish['activity_id']]);$actuals=$query->fetchAll();
 AlphaTest::same(40.0,(float)$actuals[0]['carga_kg'],'Finish actual load');AlphaTest::same(99,(int)$actuals[0]['repeticoes'],'Finish actual reps');
 $q=$pdo->prepare('SELECT duracao_segundos,distancia_metros FROM series_exercicio_atividade WHERE idregistro=? AND ordem_exercicio=5 AND ordem_serie=1');$q->execute([$finish['activity_id']]);$a=$q->fetch();
 AlphaTest::same(1500,(int)$a['duracao_segundos'],'Finish actual duration');AlphaTest::same(1500.0,(float)$a['distancia_metros'],'Finish actual distance');
 require_once dirname(__DIR__,2).'/src/function/atividade_presenter.php';$detail=atividadeDetalheApi($pdo,$finish['activity_id'],$user);
 AlphaTest::same(1500.0,$detail['forca']['exercicios'][4]['series'][0]['duracao_segundos'],'Presenter retains duration');
 $historical=sessaoCarregarPorId($pdo,$user,$sessionId);$pdo->prepare("UPDATE exercicios SET nome='Scott renamed' WHERE idexercicio=?")->execute([$scott]);
 AlphaTest::same($historical['exercicios'][3]['nome_snapshot'],sessaoCarregarPorId($pdo,$user,$sessionId)['exercicios'][3]['nome_snapshot'],'Completed session name immutable');
 $historyName=$pdo->prepare('SELECT nome_exercicio FROM series_exercicio_atividade WHERE idregistro=? AND ordem_exercicio=4 LIMIT 1');$historyName->execute([$finish['activity_id']]);$oldName=$historyName->fetchColumn();
 cronogramaRepararNomesPlano($pdo,$user,'workout',$workout);$historyName->execute([$finish['activity_id']]);
 AlphaTest::same($oldName,$historyName->fetchColumn(),'Plan repair never renames historical Activity sets');
 $next=sessaoIniciarCronograma($pdo,$user,$workout);$history=$next['exercicios'][4]['historico']['ultima'];
 AlphaTest::same(1500,(int)$history['duracao_s'],'Last time actual duration');AlphaTest::same(1500.0,(float)$history['distancia_m'],'Last time actual distance');
};
